/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void policy_spu_func_00000A00(spu_context* ctx);
void policy_spu_func_00000A60(spu_context* ctx);
void policy_spu_func_00000A90(spu_context* ctx);
void policy_spu_func_00000AAC(spu_context* ctx);
void policy_spu_func_00001690(spu_context* ctx);
void policy_spu_func_000016C8(spu_context* ctx);
void policy_spu_func_000016F8(spu_context* ctx);
void policy_spu_func_00001708(spu_context* ctx);
void policy_spu_func_0000173C(spu_context* ctx);
void policy_spu_func_000017EC(spu_context* ctx);
void policy_spu_func_00001828(spu_context* ctx);
void policy_spu_func_00001848(spu_context* ctx);
void policy_spu_func_00001910(spu_context* ctx);
void policy_spu_func_00001930(spu_context* ctx);
void policy_spu_func_000019F8(spu_context* ctx);
void policy_spu_func_00001A74(spu_context* ctx);
void policy_spu_func_00001A78(spu_context* ctx);
void policy_spu_func_00001AD8(spu_context* ctx);
void policy_spu_func_00001B00(spu_context* ctx);
void policy_spu_func_00001B28(spu_context* ctx);
void policy_spu_func_00001B4C(spu_context* ctx);
void policy_spu_func_00001B90(spu_context* ctx);
void policy_spu_func_00001C68(spu_context* ctx);
void policy_spu_func_00001CD0(spu_context* ctx);
void policy_spu_func_00001D8C(spu_context* ctx);
void policy_spu_func_00001DA8(spu_context* ctx);
void policy_spu_func_00001E84(spu_context* ctx);
void policy_spu_func_00001E98(spu_context* ctx);
void policy_spu_func_00001ED4(spu_context* ctx);
void policy_spu_func_00001F88(spu_context* ctx);
void policy_spu_func_00001F8C(spu_context* ctx);
void policy_spu_func_00002044(spu_context* ctx);
void policy_spu_func_00002050(spu_context* ctx);
void policy_spu_func_00002080(spu_context* ctx);
void policy_spu_func_00002154(spu_context* ctx);
void policy_spu_func_00002198(spu_context* ctx);
void policy_spu_func_000021C8(spu_context* ctx);
void policy_spu_func_00002238(spu_context* ctx);
void policy_spu_func_00002284(spu_context* ctx);
void policy_spu_func_00002290(spu_context* ctx);
void policy_spu_func_000022C0(spu_context* ctx);
void policy_spu_func_000022C8(spu_context* ctx);
void policy_spu_func_000022D0(spu_context* ctx);
void policy_spu_func_000022D8(spu_context* ctx);
void policy_spu_func_000022E0(spu_context* ctx);
void policy_spu_func_000022F0(spu_context* ctx);
void policy_spu_func_00002310(spu_context* ctx);
void policy_spu_func_0000233C(spu_context* ctx);
void policy_spu_func_00002368(spu_context* ctx);
void policy_spu_func_00002378(spu_context* ctx);
void policy_spu_func_00002380(spu_context* ctx);
void policy_spu_func_00002390(spu_context* ctx);
void policy_spu_func_000023A8(spu_context* ctx);
void policy_spu_func_000023B0(spu_context* ctx);
void policy_spu_func_000023C0(spu_context* ctx);
void policy_spu_func_000023C8(spu_context* ctx);
void policy_spu_func_000023DC(spu_context* ctx);
void policy_spu_func_00002480(spu_context* ctx);
void policy_spu_func_000024B8(spu_context* ctx);
void policy_spu_func_000024E0(spu_context* ctx);
void policy_spu_func_0000252C(spu_context* ctx);
void policy_spu_func_00002538(spu_context* ctx);
void policy_spu_func_00002554(spu_context* ctx);
void policy_spu_func_00002580(spu_context* ctx);
void policy_spu_func_00002598(spu_context* ctx);
void policy_spu_func_00002608(spu_context* ctx);
void policy_spu_func_00002610(spu_context* ctx);
void policy_spu_func_00002614(spu_context* ctx);
void policy_spu_func_00002618(spu_context* ctx);
void policy_spu_func_00002648(spu_context* ctx);
void policy_spu_func_00002678(spu_context* ctx);
void policy_spu_func_000026BC(spu_context* ctx);
void policy_spu_func_000026D0(spu_context* ctx);
void policy_spu_func_000027B8(spu_context* ctx);
void policy_spu_func_000027D8(spu_context* ctx);
void policy_spu_func_00002800(spu_context* ctx);
void policy_spu_func_00002860(spu_context* ctx);
void policy_spu_func_00002874(spu_context* ctx);
void policy_spu_func_000028A0(spu_context* ctx);
void policy_spu_func_000028CC(spu_context* ctx);
void policy_spu_func_000028E0(spu_context* ctx);
void policy_spu_func_00002948(spu_context* ctx);
void policy_spu_func_000029B8(spu_context* ctx);
void policy_spu_func_000029CC(spu_context* ctx);
void policy_spu_func_000029D8(spu_context* ctx);
void policy_spu_func_00002A18(spu_context* ctx);
void policy_spu_func_00002A60(spu_context* ctx);
void policy_spu_func_00002A88(spu_context* ctx);
void policy_spu_func_00002AD0(spu_context* ctx);
void policy_spu_func_00002B10(spu_context* ctx);
void policy_spu_func_00002B24(spu_context* ctx);
void policy_spu_func_00002B88(spu_context* ctx);
void policy_spu_func_00002B98(spu_context* ctx);
void policy_spu_func_00002BA0(spu_context* ctx);
void policy_spu_func_00002C30(spu_context* ctx);
void policy_spu_func_00002C38(spu_context* ctx);
void policy_spu_func_00002C78(spu_context* ctx);
void policy_spu_func_00002CB0(spu_context* ctx);
void policy_spu_func_00002CF0(spu_context* ctx);
void policy_spu_func_00002CF8(spu_context* ctx);
void policy_spu_func_00002D00(spu_context* ctx);
void policy_spu_func_00002D08(spu_context* ctx);
void policy_spu_func_00002D10(spu_context* ctx);
void policy_spu_func_00002D30(spu_context* ctx);
void policy_spu_func_00002D40(spu_context* ctx);
void policy_spu_func_00002DB0(spu_context* ctx);
void policy_spu_func_00002DB4(spu_context* ctx);
void policy_spu_func_00002DC0(spu_context* ctx);
void policy_spu_func_00002DF8(spu_context* ctx);
void policy_spu_func_00002E00(spu_context* ctx);
void policy_spu_func_00002E80(spu_context* ctx);
void policy_spu_func_00002EBC(spu_context* ctx);
void policy_spu_func_00002EE8(spu_context* ctx);
void policy_spu_func_00002F08(spu_context* ctx);
void policy_spu_func_00002F18(spu_context* ctx);
void policy_spu_func_00002F38(spu_context* ctx);
void policy_spu_func_00002FE8(spu_context* ctx);
void policy_spu_func_00003038(spu_context* ctx);
void policy_spu_func_00003040(spu_context* ctx);
void policy_spu_func_000030B0(spu_context* ctx);
void policy_spu_func_000031D4(spu_context* ctx);
void policy_spu_func_000031E0(spu_context* ctx);
void policy_spu_func_000032C8(spu_context* ctx);
void policy_spu_func_000032F0(spu_context* ctx);
void policy_spu_func_00003300(spu_context* ctx);
void policy_spu_func_00003364(spu_context* ctx);
void policy_spu_func_0000337C(spu_context* ctx);
void policy_spu_func_00003380(spu_context* ctx);
void policy_spu_func_000033C8(spu_context* ctx);
void policy_spu_func_0000344C(spu_context* ctx);
void policy_spu_func_00003450(spu_context* ctx);
void policy_spu_func_0000345C(spu_context* ctx);
void policy_spu_func_000034E8(spu_context* ctx);
void policy_spu_func_0000358C(spu_context* ctx);
void policy_spu_func_00003590(spu_context* ctx);
void policy_spu_func_000035A0(spu_context* ctx);
void policy_spu_func_000035C0(spu_context* ctx);
void policy_spu_func_000035CC(spu_context* ctx);
void policy_spu_func_00003618(spu_context* ctx);
void policy_spu_func_00003640(spu_context* ctx);
void policy_spu_func_00003650(spu_context* ctx);
void policy_spu_func_00003660(spu_context* ctx);
void policy_spu_func_00003678(spu_context* ctx);
void policy_spu_func_000036B8(spu_context* ctx);
void policy_spu_func_000036E0(spu_context* ctx);
void policy_spu_func_000037C0(spu_context* ctx);
void policy_spu_func_00003800(spu_context* ctx);
void policy_spu_func_00003868(spu_context* ctx);
void policy_spu_func_000038A4(spu_context* ctx);
void policy_spu_func_0003FEC0(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void policy_spu_recomp_register(void);
