/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_func_00000A00(spu_context* ctx);
void spu_func_00001690(spu_context* ctx); /* external */
void spu_func_00001B28(spu_context* ctx); /* external */
void spu_func_000022D0(spu_context* ctx); /* external */
void spu_func_000022E0(spu_context* ctx); /* external */
void spu_func_00002310(spu_context* ctx); /* external */
void spu_func_000023C8(spu_context* ctx); /* external */
void spu_func_00002610(spu_context* ctx); /* external */
void spu_func_00002618(spu_context* ctx); /* external */
void spu_func_00002648(spu_context* ctx); /* external */
void spu_func_00002678(spu_context* ctx); /* external */
void spu_func_000026D0(spu_context* ctx); /* external */
void spu_func_000027B8(spu_context* ctx); /* external */
void spu_func_00002874(spu_context* ctx); /* external */
void spu_func_000028A0(spu_context* ctx); /* external */
void spu_func_000028E0(spu_context* ctx); /* external */
void spu_func_00002948(spu_context* ctx); /* external */
void spu_func_000029D8(spu_context* ctx); /* external */
void spu_func_00002AD0(spu_context* ctx); /* external */
void spu_func_00002D40(spu_context* ctx); /* external */
void spu_func_00002E00(spu_context* ctx); /* external */
void spu_func_00002E80(spu_context* ctx); /* external */
void spu_func_00002EE8(spu_context* ctx); /* external */
void spu_func_00002F38(spu_context* ctx); /* external */
void spu_func_000031E0(spu_context* ctx); /* external */
void spu_func_00003380(spu_context* ctx); /* external */
void spu_func_000035A0(spu_context* ctx); /* external */
void spu_func_000035C0(spu_context* ctx); /* external */
void spu_func_000035CC(spu_context* ctx); /* external */
void spu_func_00003618(spu_context* ctx); /* external */
void spu_func_00003640(spu_context* ctx); /* external */
void spu_func_00003650(spu_context* ctx); /* external */
void spu_func_00003660(spu_context* ctx); /* external */
void spu_func_00003678(spu_context* ctx); /* external */
void spu_func_000036E0(spu_context* ctx); /* external */
void spu_func_000037C0(spu_context* ctx); /* external */
void spu_func_00003868(spu_context* ctx); /* external */
void spu_func_00006000(spu_context* ctx); /* external */
void spu_func_00018180(spu_context* ctx); /* external */
void spu_func_0003FEC0(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_recomp_register(void);
