/*
 * ps3recomp - PPU runtime loader
 *
 * The runtime half of the static recompiler's PPU side. It provides everything
 * the lifted code (ppu_recomp.c, generated by ppu_lifter.py) expects from "the
 * game project":
 *
 *   - big-endian guest memory accessors (vm_read / vm_write),
 *   - the address -> function registry + ps3_indirect_call dispatch,
 *   - the cross-fragment trampoline TLS pointer,
 *   - an lv2_syscall stub,
 *   - an ELF image loader (PT_LOAD -> vm_base, BSS zeroed),
 *   - OPD resolution ({u32 func, u32 toc}) and a run entry point.
 *
 * Game-agnostic: works on any decrypted PS3 PPU ELF. `vm_base` is owned by the
 * host (allocated large enough to cover the highest segment vaddr+memsz).
 *
 * Compiled as C++ to match the lifted output's `extern "C"` / __declspec(thread).
 */

#include "ppu_recomp.h"     /* ppu_context, func decls, ppu_recomp_register */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mutex>

extern "C" uint8_t* vm_base;   /* defined by the host */

/* Guest address-space size (host sets this); 0 = unchecked. Bounds-checking
 * turns a stray pointer in lifted code into a logged bad-access returning 0
 * instead of a host segfault -- so a first-boot run reveals the next wall
 * rather than dying. */
extern "C" uint64_t ppu_vm_size = 0;

/* The game exposes one current GCM command context through a process-global
 * guest pointer. Host PPU threads must not interleave begin/end pairs. */
static std::recursive_mutex s_gcm_context_mutex;

extern "C" void ps3_gcm_context_lock(void)
{
    s_gcm_context_mutex.lock();
}

extern "C" void ps3_gcm_context_unlock(void)
{
    s_gcm_context_mutex.unlock();
}

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <process.h>
#include <dbghelp.h>
#pragma comment(lib, "dbghelp.lib")
/* Symbolize the nearest lifted func_* on the host call stack to name the guest
 * function performing a bad access. Walks a few frames since vm_read/write and
 * the bounds helper sit between the lifted code and here. */
static void vm_dump_guest_caller(uint32_t a)
{
    static int syminit = 0;
    HANDLE proc = GetCurrentProcess();
    if (!syminit) { SymInitialize(proc, NULL, TRUE); syminit = 1; }
    void* frames[24];
    USHORT n = CaptureStackBackTrace(0, 24, frames, NULL);
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO* sym = (SYMBOL_INFO*)buf;
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    fprintf(stderr, "[vm] first bad access 0x%08X — host stack (looking for func_*):\n", a);
    for (USHORT i = 0; i < n; i++) {
        DWORD64 disp = 0;
        if (SymFromAddr(proc, (DWORD64)(uintptr_t)frames[i], &disp, sym)) {
            IMAGEHLP_LINE64 line = {};
            line.SizeOfStruct = sizeof(line);
            DWORD line_disp = 0;
            if (SymGetLineFromAddr64(proc, (DWORD64)(uintptr_t)frames[i], &line_disp, &line))
                fprintf(stderr, "      [%u] %s +0x%llX (%s:%lu)\n", i, sym->Name,
                        (unsigned long long)disp, line.FileName, line.LineNumber);
            else
                fprintf(stderr, "      [%u] %s +0x%llX\n", i, sym->Name, (unsigned long long)disp);
        }
    }
}
extern "C" void ppu_dump_guest_caller(uint32_t tag) { vm_dump_guest_caller(tag); }

static void vm_dump_suspended_stack(HANDLE thread, CONTEXT context)
{
    HANDLE proc = GetCurrentProcess();
    STACKFRAME64 frame = {};
    frame.AddrPC.Offset = context.Rip;
    frame.AddrPC.Mode = AddrModeFlat;
    frame.AddrFrame.Offset = context.Rbp;
    frame.AddrFrame.Mode = AddrModeFlat;
    frame.AddrStack.Offset = context.Rsp;
    frame.AddrStack.Mode = AddrModeFlat;
    fprintf(stderr, "[hb-stack] suspended main thread:\n");
    for (unsigned i = 0; i < 16; i++) {
        if (!StackWalk64(IMAGE_FILE_MACHINE_AMD64, proc, thread, &frame, &context,
                         nullptr, SymFunctionTableAccess64, SymGetModuleBase64, nullptr))
            break;
        if (!frame.AddrPC.Offset) break;
        char buf[sizeof(SYMBOL_INFO) + 256] = {};
        SYMBOL_INFO* sym = (SYMBOL_INFO*)buf;
        sym->SizeOfStruct = sizeof(SYMBOL_INFO);
        sym->MaxNameLen = 255;
        DWORD64 disp = 0;
        if (!SymFromAddr(proc, frame.AddrPC.Offset, &disp, sym)) continue;
        IMAGEHLP_LINE64 line = {};
        line.SizeOfStruct = sizeof(line);
        DWORD line_disp = 0;
        if (SymGetLineFromAddr64(proc, frame.AddrPC.Offset, &line_disp, &line))
            fprintf(stderr, "   [%u] %s +0x%llX (%s:%lu)\n", i, sym->Name,
                    (unsigned long long)disp, line.FileName, line.LineNumber);
        else
            fprintf(stderr, "   [%u] %s +0x%llX\n", i, sym->Name, (unsigned long long)disp);
    }
}
#else
static void vm_dump_guest_caller(uint32_t) {}
extern "C" void ppu_dump_guest_caller(uint32_t) {}
#endif

static int vm_oob(uint32_t a, uint32_t n)
{
    if (ppu_vm_size && (uint64_t)a + n > ppu_vm_size) {
        static uint64_t total = 0;
        static int logged = 0;
        total++;
        if (logged < 10) {
            fprintf(stderr, "[vm] OOB access 0x%08X (+%u)\n", a, n);
            static int bt = 0;
            if (a >= 0xFFFF0000u && !bt) { bt = 1; vm_dump_guest_caller(a); }
            logged++;
        } else if ((total % 1000000) == 0) {
            fprintf(stderr, "[vm] OOB heartbeat: %llu total (last 0x%08X)\n",
                    (unsigned long long)total, a);
        }
        return 1;
    }
    return 0;
}

/* ---------------------------------------------------------------------------
 * Big-endian guest memory accessors (PPU is big-endian; vm_base holds the
 * guest image in its native byte order).
 * -----------------------------------------------------------------------*/
extern "C" {
uint8_t  vm_read8 (uint64_t a) { if (vm_oob((uint32_t)a,1)) return 0;
    if ((uint32_t)a == 0x00DED7DAu) {
        static volatile LONG traced = 0;
        if (InterlockedCompareExchange(&traced, 1, 0) == 0)
            vm_dump_guest_caller((uint32_t)a);
    }
#ifdef VM_SAMPLE_READS
    { static uint64_t c=0; if ((++c % 2000000ull)==0) fprintf(stderr, "[sample] read8  0x%08X ra0=%p ra1=%p\n", (uint32_t)a, __builtin_return_address(0), __builtin_return_address(1)); }
#endif
    return vm_base[(uint32_t)a]; }
uint16_t vm_read16(uint64_t a) { if (vm_oob((uint32_t)a,2)) return 0; uint16_t v; memcpy(&v, vm_base + (uint32_t)a, 2); return __builtin_bswap16(v); }
uint32_t vm_read32(uint64_t a) { if (vm_oob((uint32_t)a,4)) return 0; uint32_t v; memcpy(&v, vm_base + (uint32_t)a, 4);
#ifdef VM_SAMPLE_READS
    { static uint64_t c=0; if ((++c % 4000000ull)==0) fprintf(stderr, "[sample] read32 0x%08X = 0x%08X\n", (uint32_t)a, __builtin_bswap32(v)); }
#endif
    return __builtin_bswap32(v); }
uint64_t vm_read64(uint64_t a) { if (vm_oob((uint32_t)a,8)) return 0; uint64_t v; memcpy(&v, vm_base + (uint32_t)a, 8);
#ifdef VM_SAMPLE_READS
    { static uint64_t c=0; if ((++c % 2000000ull)==0) fprintf(stderr, "[sample] read64 0x%08X\n", (uint32_t)a); }
#endif
    return __builtin_bswap64(v); }
void ppu_watch_hit(unsigned int addr, unsigned long long val);   /* fwd */
#define PPU_WATCH_ADDR 0x011DFDA8u
void vm_write8 (uint64_t a, uint8_t  v) { if (vm_oob((uint32_t)a,1)) return; if ((uint32_t)a==PPU_WATCH_ADDR) ppu_watch_hit((uint32_t)a,v); vm_base[(uint32_t)a] = v; }
void vm_write16(uint64_t a, uint16_t v) { if (vm_oob((uint32_t)a,2)) return; if ((uint32_t)a<=PPU_WATCH_ADDR&&PPU_WATCH_ADDR<(uint32_t)a+2) ppu_watch_hit((uint32_t)a,v); v = __builtin_bswap16(v); memcpy(vm_base + (uint32_t)a, &v, 2); }
void vm_write32(uint64_t a, uint32_t v) { if (vm_oob((uint32_t)a,4)) return; if ((uint32_t)a<=PPU_WATCH_ADDR&&PPU_WATCH_ADDR<(uint32_t)a+4) ppu_watch_hit((uint32_t)a,v); v = __builtin_bswap32(v); memcpy(vm_base + (uint32_t)a, &v, 4); }
void vm_write64(uint64_t a, uint64_t v) { if (vm_oob((uint32_t)a,8)) return; if ((uint32_t)a<=PPU_WATCH_ADDR&&PPU_WATCH_ADDR<(uint32_t)a+8) ppu_watch_hit((uint32_t)a,v); v = __builtin_bswap64(v); memcpy(vm_base + (uint32_t)a, &v, 8); }
void vm_store_vec(uint32_t ea, const void* src) { if (vm_oob(ea,16)) return; if (ea<=PPU_WATCH_ADDR&&PPU_WATCH_ADDR<ea+16) ppu_watch_hit(ea, *(const unsigned long long*)src); memcpy(vm_base + ea, src, 16); }
}

/* Cross-fragment trampoline pointer (matches the lifted header's TLS decl). */
extern "C" __declspec(thread) void (*g_trampoline_fn)(void*) = nullptr;

/* Canonical TOC (r2) for this single-TOC static binary. Captured at ppu_run.
 * The whole EBOOT shares one TOC, so r2==0 anywhere is always a lost-TOC bug;
 * the trampoline drain restores it. */
extern "C" uint32_t g_canonical_toc = 0;

/* Trampoline-chain tracer (bring-up diagnostic). Every DRAIN_TRAMPOLINE tail
 * call records its target here; on a crash/runaway we dump the last N targets
 * (reverse-mapped host fn ptr -> guest func_ addr via function_table) to reveal
 * the exact lifted chain — ad-hoc per-function logging can't see tail-call
 * chains, but this can. */
#define PPU_TRAMP_RING 64
extern "C" { void* g_tramp_ring[PPU_TRAMP_RING]; unsigned g_tramp_idx; }
static uint32_t tramp_addr_of(void* fn) {
    for (uint64_t i = 0; i < function_table_count; i++)
        if ((void*)function_table[i].func == fn) return (uint32_t)function_table[i].addr;
    return 0;
}
static void ppu_tramp_dump(void)
{
    fprintf(stderr, "[tramp] last %d trampoline targets (oldest first):\n", PPU_TRAMP_RING);
    for (unsigned k = 0; k < PPU_TRAMP_RING; k++) {
        void* fn = g_tramp_ring[(g_tramp_idx + k) & (PPU_TRAMP_RING - 1)];
        fprintf(stderr, "   func_%08X\n", fn ? tramp_addr_of(fn) : 0);
    }
}
extern "C" void ppu_tramp_dump_c(void) { ppu_tramp_dump(); }
/* Bring-up watch: log writes to a specific guest address + the guest caller.
 * Used to find which init writes garbage (0x18191A1B) into the singleton vtable
 * at guest 0x013BF820. */
extern "C" void ppu_watch_hit(unsigned int addr, unsigned long long val) {
    fprintf(stderr, "[watch] write 0x%08X = 0x%016llX\n", addr, val);
    vm_dump_guest_caller(0);
    /* reliable guest attribution: last 6 indirect-call trampoline targets */
    fprintf(stderr, "      recent guest indirect-calls:");
    for (int k = 1; k <= 6; k++) { void* fn = g_tramp_ring[(g_tramp_idx - k) & (PPU_TRAMP_RING - 1)]; fprintf(stderr, " func_%08X", fn ? tramp_addr_of(fn) : 0); }
    fprintf(stderr, "\n");
}
extern "C" { volatile unsigned long long g_tramp_count = 0; }
extern "C" { volatile unsigned long long g_ind_count = 0; }   /* indirect calls */
static void ppu_ind_dump(void);

/* Temporary bring-up profiler for indirect targets. A fixed lock-free table
 * keeps the hot path cheap enough to reveal callback loops during boot. */
#define PPU_IND_PROFILE_SIZE (1u << 16)
struct ppu_ind_profile_slot { volatile LONG target; volatile LONG64 count; };
static ppu_ind_profile_slot g_ind_profile[PPU_IND_PROFILE_SIZE];

static void ppu_ind_profile_hit(uint32_t target)
{
    uint32_t i = (target * 2654435761u) & (PPU_IND_PROFILE_SIZE - 1);
    for (uint32_t p = 0; p < PPU_IND_PROFILE_SIZE; p++) {
        LONG seen = g_ind_profile[i].target;
        if (seen == (LONG)target ||
            (seen == 0 && InterlockedCompareExchange(&g_ind_profile[i].target,
                                                     (LONG)target, 0) == 0)) {
            InterlockedIncrement64(&g_ind_profile[i].count);
            return;
        }
        i = (i + 1) & (PPU_IND_PROFILE_SIZE - 1);
    }
}

static void ppu_ind_profile_dump(void)
{
    struct hot_entry { uint32_t target; LONG64 count; } top[8] = {};
    for (uint32_t i = 0; i < PPU_IND_PROFILE_SIZE; i++) {
        LONG64 count = g_ind_profile[i].count;
        if (count <= top[7].count) continue;
        uint32_t pos = 7;
        while (pos && count > top[pos - 1].count) {
            top[pos] = top[pos - 1];
            pos--;
        }
        top[pos] = { (uint32_t)g_ind_profile[i].target, count };
    }
    fprintf(stderr, "[ind-profile]");
    for (const hot_entry& entry : top)
        if (entry.count) fprintf(stderr, " %08X=%lld", entry.target, (long long)entry.count);
    fprintf(stderr, "\n");
}

int g_pf_dbg = 0;
extern "C" void ppu_tramp_rec(void* fn) { g_tramp_ring[g_tramp_idx++ & (PPU_TRAMP_RING - 1)] = fn; g_tramp_count++; }

/* Heartbeat: every ~2s print the tail-call throughput delta and the most recent
 * trampoline target. Steady delta with CHANGING targets = real progress; delta
 * ~0 or the same func repeating = a stuck loop. Bring-up visibility only. */
extern "C" HANDLE g_main_thread;
static unsigned __stdcall ppu_heartbeat(void*)
{
    unsigned long long prev = 0;
    for (;;) {
        Sleep(2000);
        unsigned long long now = g_tramp_count;
        static unsigned long long prev_ind = 0;
        unsigned long long ind = g_ind_count;
        void* fn = g_tramp_ring[(g_tramp_idx - 1) & (PPU_TRAMP_RING - 1)];
        fprintf(stderr, "[hb] +%llu tail-calls, +%llu indirect, last=func_%08X\n",
                now - prev, ind - prev_ind, fn ? tramp_addr_of(fn) : 0);
        ppu_ind_profile_dump();
        if (now == prev && ind - prev_ind > 1000000ull) {
            static int dumped_indirect_spin = 0;
            if (!dumped_indirect_spin++) ppu_ind_dump();
        }
        /* Runaway tail-call cycle (not a stall): dump the ring once to reveal the
         * cycle members so the loop can be broken at the right function. */
        if ((now - prev) > 1000000ull) { static int _d=0; if(_d<1){_d++; ppu_tramp_dump(); } }
        /* Stall detected (no tail-calls AND no indirect-calls): the main thread
         * is spinning in a callless loop the trampoline ring can't see. Suspend
         * it, sample its RIP, symbolize -> the actual spinning host function. */
        if (now == prev && ind == prev_ind && g_main_thread) {
            SuspendThread(g_main_thread);
            CONTEXT c; c.ContextFlags = CONTEXT_CONTROL;
            if (GetThreadContext(g_main_thread, &c)) {
                char buf[sizeof(SYMBOL_INFO) + 256] = {0};
                SYMBOL_INFO* si = (SYMBOL_INFO*)buf;
                si->SizeOfStruct = sizeof(SYMBOL_INFO); si->MaxNameLen = 255;
                DWORD64 disp = 0;
                if (SymFromAddr(GetCurrentProcess(), c.Rip, &disp, si))
                    fprintf(stderr, "[hb-ip] main thread spinning in %s +0x%llX\n", si->Name, (unsigned long long)disp);
                else
                    fprintf(stderr, "[hb-ip] main RIP=0x%llX (no symbol)\n", (unsigned long long)c.Rip);
                IMAGEHLP_LINE64 line = {};
                line.SizeOfStruct = sizeof(line);
                DWORD line_disp = 0;
                if (SymGetLineFromAddr64(GetCurrentProcess(), c.Rip, &line_disp, &line))
                    fprintf(stderr, "[hb-line] %s:%lu (+0x%lX)\n",
                            line.FileName, line.LineNumber, line_disp);
                static int dumped_stall_stack = 0;
                if (dumped_stall_stack++ < 20) vm_dump_suspended_stack(g_main_thread, c);
            }
            ResumeThread(g_main_thread);
        }
        prev = now; prev_ind = ind;
    }
    return 0;
}
extern "C" HANDLE g_main_thread = 0;
extern "C" void ppu_start_heartbeat(void)
{
    DuplicateHandle(GetCurrentProcess(), GetCurrentThread(), GetCurrentProcess(),
                    &g_main_thread, 0, FALSE, DUPLICATE_SAME_ACCESS);
    SymInitialize(GetCurrentProcess(), nullptr, TRUE);
    _beginthreadex(nullptr, 0, ppu_heartbeat, nullptr, 0, nullptr);
}

/* Per-thread guest call depth (lifted functions increment/decrement via the
 * PpuDepthGuard emitted in each function). Bounds runaway recursion from
 * half-initialized engine structures during bring-up. */
extern "C" __declspec(thread) int g_ppu_depth = 0;

/* PT_TLS image info captured by ppu_load_elf, consumed by sys_initialize_tls
 * when the CRT passes zero TLS params (it reads them from a process-param
 * structure we don't fully populate). */
extern "C" uint32_t g_tls_vaddr  = 0;
extern "C" uint32_t g_tls_filesz = 0;
extern "C" uint32_t g_tls_memsz  = 0;

/* User-memory accounting for sys_memory_get_user_memory_size (syscall 352).
 * RPCS3 ground truth: Total=0xD500000 (213 MB). `available` is DYNAMIC =
 * total - (loaded game image + runtime allocations). The game derives
 * "code and data size = total - available" and aborts if it exceeds the
 * budget. At the first budget check it must read avail≈0xBFE0000 (191.875 MB)
 * so code+data≈21.125 MB. g_user_allocated is seeded with the loaded PT_LOAD
 * image size at ELF load and grows with runtime allocations. */
extern "C" uint64_t g_user_total     = 0x0D500000ull;
extern "C" uint64_t g_user_allocated = 0;

/* ---------------------------------------------------------------------------
 * Function registry: guest code address -> lifted host function.
 * Open-addressing hash (load factor kept low). A large EBOOT lifts to 80k+
 * entries (base functions + mid-function entry points), so the table must be
 * comfortably larger than that or insertion spins forever once it fills. At 18
 * bits (262144 slots) an 83k-entry table sits at ~32% load — healthy for open
 * addressing. Bump PPU_HASH_BITS if a future game exceeds ~170k entries.
 * -----------------------------------------------------------------------*/
typedef void (*ppu_fn)(ppu_context*);

#define PPU_HASH_BITS 18
#define PPU_HASH_SIZE (1u << PPU_HASH_BITS)
#define PPU_HASH_MASK (PPU_HASH_SIZE - 1)

static uint32_t g_addr[PPU_HASH_SIZE];
static ppu_fn   g_fn[PPU_HASH_SIZE];
static uint32_t g_fn_count = 0;

extern "C" void ppu_register_function(uint64_t addr, ppu_fn fn)
{
    uint32_t a = (uint32_t)addr;
    uint32_t i = (a * 2654435761u) & PPU_HASH_MASK;
    for (uint32_t probes = 0; probes < PPU_HASH_SIZE; probes++) {
        if (g_fn[i] == nullptr) { g_addr[i] = a; g_fn[i] = fn; g_fn_count++; return; }
        if (g_addr[i] == a) { g_fn[i] = fn; return; }   /* overwrite */
        i = (i + 1) & PPU_HASH_MASK;
    }
    /* Table full — should never happen given PPU_HASH_BITS sizing. Log once
     * rather than spinning forever. */
    static int warned = 0;
    if (!warned) { warned = 1;
        fprintf(stderr, "[ppu] FATAL: function table full (%u entries) — raise PPU_HASH_BITS\n", g_fn_count); }
}

static ppu_fn ppu_lookup(uint32_t a)
{
    uint32_t i = (a * 2654435761u) & PPU_HASH_MASK;
    for (uint32_t probes = 0; probes < PPU_HASH_SIZE; probes++) {
        if (g_fn[i] == nullptr) return nullptr;
        if (g_addr[i] == a) return g_fn[i];
        i = (i + 1) & PPU_HASH_MASK;
    }
    return nullptr;
}

extern "C" uint32_t ppu_function_count(void) { return g_fn_count; }

/* Bridge the lifter-emitted function_table[] (declared in ppu_recomp.h) into the
 * address->function hash map. The host boot harness calls this once at startup. */
extern "C" void ppu_recomp_register(void)
{
    for (uint64_t i = 0; i < function_table_count; i++)
        ppu_register_function(function_table[i].addr, function_table[i].func);
}

/* ---------------------------------------------------------------------------
 * Firmware import resolution (PS3 lazy-binding PLT).
 *
 * UC3 and other "statically linked" PS3 executables import firmware functions
 * via a _sys_prx_param (PT_PRX_PARAM, type 0x60000002) structure that lists,
 * per module, parallel arrays of NIDs and stub addresses. Each call to an
 * import goes through a stub whose address we see in r12 at the (failed)
 * indirect call. We map stub_addr -> NID here and route the call to the HLE
 * dispatcher (ps3_hle_call), which marshals the PPC ABI to our C handlers.
 * -----------------------------------------------------------------------*/
extern "C" void ps3_hle_call(uint32_t nid, ppu_context* ctx);

#define IMPORT_MAP_BITS 11
#define IMPORT_MAP_SIZE (1u << IMPORT_MAP_BITS)
#define IMPORT_MAP_MASK (IMPORT_MAP_SIZE - 1)
static uint32_t g_import_stub[IMPORT_MAP_SIZE];  /* stub addr (0 = empty) */
static uint32_t g_import_nid[IMPORT_MAP_SIZE];
static uint32_t g_import_count = 0;

static void import_map_add(uint32_t stub_addr, uint32_t nid)
{
    if (!stub_addr) return;
    uint32_t i = (stub_addr * 2654435761u) & IMPORT_MAP_MASK;
    for (uint32_t p = 0; p < IMPORT_MAP_SIZE; p++) {
        if (g_import_stub[i] == 0) { g_import_stub[i] = stub_addr; g_import_nid[i] = nid; g_import_count++; return; }
        if (g_import_stub[i] == stub_addr) { g_import_nid[i] = nid; return; }
        i = (i + 1) & IMPORT_MAP_MASK;
    }
}

static int import_map_find(uint32_t stub_addr, uint32_t* nid_out)
{
    if (!stub_addr) return 0;
    uint32_t i = (stub_addr * 2654435761u) & IMPORT_MAP_MASK;
    for (uint32_t p = 0; p < IMPORT_MAP_SIZE; p++) {
        if (g_import_stub[i] == 0) return 0;
        if (g_import_stub[i] == stub_addr) { *nid_out = g_import_nid[i]; return 1; }
        i = (i + 1) & IMPORT_MAP_MASK;
    }
    return 0;
}

/* Parse the _sys_prx_param import tables from guest memory (already loaded by
 * ppu_load_elf) and build the stub->NID map. prx_param_vaddr comes from the
 * PT_PRX_PARAM program header. Safe to call once after the ELF is loaded. */
extern "C" void ppu_resolve_imports(uint32_t prx_param_vaddr)
{
    if (!prx_param_vaddr || !vm_base) {
        fprintf(stderr, "[ppu] no PRX_PARAM — firmware imports will be unresolved\n");
        return;
    }
    uint32_t magic       = vm_read32(prx_param_vaddr + 4);
    uint32_t libstubstart = vm_read32(prx_param_vaddr + 0x18);
    uint32_t libstubend   = vm_read32(prx_param_vaddr + 0x1C);
    if (magic != 0x1B434CECu) {
        fprintf(stderr, "[ppu] PRX_PARAM bad magic 0x%08X\n", magic);
        return;
    }
    uint32_t va = libstubstart;
    int modules = 0;
    while (va + 0x1C <= libstubend) {
        uint8_t  ssize    = vm_read8(va);
        if (ssize < 0x1C) break;
        uint16_t num_func = vm_read16(va + 6);
        uint32_t nidtab   = vm_read32(va + 0x14);
        uint32_t stubtab  = vm_read32(va + 0x18);
        for (uint16_t i = 0; i < num_func; i++) {
            uint32_t nid  = vm_read32(nidtab  + (uint32_t)i * 4);
            uint32_t stub = vm_read32(stubtab + (uint32_t)i * 4);
            import_map_add(stub, nid);
        }
        modules++;
        va += ssize;
    }
    fprintf(stderr, "[ppu] resolved %u firmware imports across %d modules\n",
            g_import_count, modules);
}

/* Central runaway-recursion guard. Incomplete HLE during bring-up can leave an
 * engine structure half-built so a recursive descent (tree/visitor walk) never
 * terminates. Every such cycle passes through at least one indirect call, so a
 * depth counter here bounds it cheaply (no per-function cost) — far better than
 * the RAII guard that exploded MSVC compile time. On overflow we bail (the
 * offending step is left incomplete) instead of overflowing the host stack. */
static __declspec(thread) int g_ind_depth = 0;
#ifndef PPU_MAX_IND_DEPTH
#define PPU_MAX_IND_DEPTH 512   /* legit indirect-call nesting is shallow; a
                                 * malformed engine data structure (scene graph
                                 * built before its deps) recurses unboundedly —
                                 * bail well before the host stack / VM commit
                                 * is exhausted, leaving that init step partial. */
#endif

/* Indirect-call target ring (bring-up): the guest ctr of every dispatched
 * indirect call, dumped on the recursion bail to reveal the cycle. */
#define PPU_IND_RING 96
static uint32_t g_ind_ring[PPU_IND_RING];
static unsigned g_ind_ring_idx;
static void ppu_ind_dump(void)
{
    fprintf(stderr, "[ind] last %d indirect-call ctr targets (oldest first):\n", PPU_IND_RING);
    for (unsigned k = 0; k < PPU_IND_RING; k++)
        fprintf(stderr, "   0x%08X\n", g_ind_ring[(g_ind_ring_idx + k) & (PPU_IND_RING - 1)]);
}

static void ppu_drain_indirect_callee(ppu_context* ctx)
{
    while (g_trampoline_fn) {
        void (*next)(void*) = g_trampoline_fn;
        g_trampoline_fn = nullptr;
        ppu_tramp_rec((void*)next);
        if (g_canonical_toc)
            ctx->gpr[2] = g_canonical_toc;
        next(ctx);
    }
}

/* Indirect dispatch core. `preserve`=true for bctrl (real CALL: enforce the
 * callee-saved ABI by save/restoring r14-r31, fixing truncated callees that
 * clobber a caller's loop counter). `preserve`=false for bctr (computed JUMP /
 * tail / gcc switch-case: the target shares the caller's frame and LEGITIMATELY
 * modifies r14-r31 — restoring them there corrupts the formatter's switch-case
 * register handoff, e.g. func_00D7A608 leaving the printf context = 0x06900000). */
static void ps3_ind_impl(ppu_context* ctx, bool preserve)
{
    extern volatile unsigned long long g_ind_count; g_ind_count++;
    uint32_t target = (uint32_t)ctx->ctr;
    ppu_fn fn = ppu_lookup(target);
    if (fn) {
        ppu_ind_profile_hit(target);
        if (target == 0x0074A438u) {
            static volatile LONG overflow_calls = 0;
            LONG overflow_call = InterlockedIncrement(&overflow_calls);
            if (overflow_call <= 4) {
                uint32_t context = (uint32_t)ctx->gpr[3];
                fprintf(stderr,
                        "[gcm-overflow] call=%ld tid=%llu context=%08X needed=%08X "
                        "begin=%08X end=%08X current=%08X callback=%08X\n",
                        overflow_call, (unsigned long long)ctx->thread_id, context,
                        (uint32_t)ctx->gpr[4], vm_read32(context + 0x0),
                        vm_read32(context + 0x4), vm_read32(context + 0x8),
                        vm_read32(context + 0xC));
                vm_dump_guest_caller(target);
            }
        }
        if (target == 0x008AC6C8u) {
            static volatile LONG64 hot_calls = 0;
            LONG64 hot_call = InterlockedIncrement64(&hot_calls);
            if (hot_call == 1 || hot_call == 3000000) {
                fprintf(stderr,
                        "[probe8ac6c8] call=%lld tid=%llu preserve=%d r3=%08X r4=%08X "
                        "r5=%08X r6=%08X sp=%08X lr=%08X\n",
                        (long long)hot_call, (unsigned long long)ctx->thread_id,
                        preserve ? 1 : 0, (uint32_t)ctx->gpr[3], (uint32_t)ctx->gpr[4],
                        (uint32_t)ctx->gpr[5], (uint32_t)ctx->gpr[6],
                        (uint32_t)ctx->gpr[1], (uint32_t)ctx->lr);
                vm_dump_guest_caller(target);
            }
        }
        /* Single-TOC binary: r2 is reserved for the TOC and must always equal
         * the canonical value. Indirect dispatch sets r2 from the OPD's toc
         * word, which can be 0 or garbage if the pointer was mis-derived;
         * normalize it so the callee's TOC-relative loads resolve. */
        if (g_canonical_toc && (uint32_t)ctx->gpr[2] != g_canonical_toc)
            ctx->gpr[2] = g_canonical_toc;
        g_ind_ring[g_ind_ring_idx++ & (PPU_IND_RING - 1)] = (uint32_t)ctx->ctr;
        if (g_ind_depth >= PPU_MAX_IND_DEPTH) {
            static int warned = 0;
            if (warned < 3) { fprintf(stderr, "[ppu] recursion depth limit at 0x%08X — bailing\n", (uint32_t)ctx->ctr); ppu_ind_dump(); warned++; }
            return;
        }
        g_ind_depth++;
        /* Enforce the PPC callee-saved ABI across indirect calls. A bctrl callee
         * MUST preserve r14-r31; some lifted functions violate this (a still-
         * truncated fn whose epilogue restoring rNN is orphaned), which corrupts
         * caller loop counters (e.g. func_001FDFE0's r31 -> OOB table index ->
         * garbage dispatch 0x18191A1B) and the global ctor walk's r31. Saving and
         * restoring them here is semantically correct (callees must preserve
         * them) and unblocks bring-up; we also log the offender once so the real
         * fix (extend its find_functions boundary) can be applied later. */
        if (preserve) {
            uint64_t saved[18]; for (int i = 0; i < 18; i++) saved[i] = ctx->gpr[14 + i];
            fn(ctx);
            /* A lifted indirect callee can return with an internal branch in
             * g_trampoline_fn.  That continuation is still part of the callee
             * and must run before the caller's nonvolatile GPRs are restored. */
            ppu_drain_indirect_callee(ctx);
            for (int i = 0; i < 18; i++)
                if (ctx->gpr[14 + i] != saved[i]) ctx->gpr[14 + i] = saved[i];
        } else {
            fn(ctx);   /* bctr: no ABI restore — target shares the frame */
        }
        g_ind_depth--;
        return;
    }

    /* Unresolved firmware import stub.
     *
     * UC3 is "statically linked" but still imports firmware functions through a
     * lazy-binding PLT: a call site loads a pointer from a GOT slot and
     * dereferences it as an OPD. Before the firmware resolves the import, that
     * GOT slot points back at the import stub itself (e.g. 0x0112BC5C ->
     * 0x00D96C54), whose first instruction is `li r12,0` (0x39800000). The
     * OPD-deref reads 0x39800000 into CTR (unresolved) and r12 holds the stub's
     * own address; calling it would recurse forever.
     *
     * We don't yet resolve these imports (parse _sys_prx_param, map each stub
     * to its NID, point it at an HLE handler). Until then, detect the stub
     * signature and return safely instead of recursing/crashing, logging the
     * stub address so it can be wired up. The caller restores its own TOC from
     * its save slot, so leaving r2 as-is here is harmless. */
    {
        uint32_t r12 = (uint32_t)ctx->gpr[12];
        uint32_t first = r12 ? vm_read32(r12) : 0;
        if ((uint32_t)ctx->ctr == 0x39800000u ||
            (first & 0xFFFF0000u) == 0x39800000u /* li r12,0 */) {
            uint32_t nid = 0;
            if (import_map_find(r12, &nid)) {
                /* Resolved firmware import — route to the HLE handler.
                 * The lifted stub saved the caller's TOC at sp+0x28 then
                 * clobbered r2 with the bogus OPD's toc word before reaching
                 * here; restore the real TOC from that slot after the call so
                 * the caller continues with a valid r2. */
                uint64_t saved_toc = vm_read64(ctx->gpr[1] + 0x28);
                ps3_hle_call(nid, ctx);
                ctx->gpr[2] = saved_toc;
                return;
            }
            static int logged = 0;
            if (logged < 40) {
                fprintf(stderr, "[ppu] import stub 0x%08X not in PRX_PARAM map (returning 0)\n", r12);
                logged++;
            }
            ctx->gpr[3] = 0;   /* CELL_OK so boot continues */
            return;
        }
    }
    /* Stuck-loop guard: a divergence (e.g. an object with a null function
     * pointer) can make the game spin on the same unresolved target forever.
     * Detect a long run of identical unresolved targets and bail so the run
     * stays fast and the log readable. */
    static uint32_t last = 0xFFFFFFFFu; static uint32_t streak = 0;
    uint32_t cur = (uint32_t)ctx->ctr;
    if (cur == last) {
        if (++streak == 2000) { fprintf(stderr, "[ppu] FATAL: stuck calling 0x%08X (%u times) -- aborting run\n", cur, streak); fflush(stderr); exit(3); }
        return;   /* don't spam the log on a tight retry loop */
    }
    last = cur; streak = 0;
    fprintf(stderr, "[ppu] unresolved indirect call -> 0x%08X\n", (uint32_t)ctx->ctr);
    static int dumped_garbage = 0;
    {
        uint32_t c = (uint32_t)ctx->ctr;
        /* ASCII-digit-looking target (e.g. 0x30303030="0000") = the numeric
         * formatter dispatching its own output string as a code pointer. Dump
         * the guest caller to pinpoint the broken numeric-conversion site. */
        bool ascii = true; for (int s = 0; s < 32; s += 8) { uint8_t b = (c >> s) & 0xFF; if (b && (b < 0x20 || b > 0x7E)) { ascii = false; break; } }
        if (((c == 0x18191A1Bu) || ascii) && dumped_garbage < 4) {
            dumped_garbage++;
            fprintf(stderr, "[ppu] >>> garbage dispatch ctr=0x%08X (r3=0x%08X) caller chain:\n", c, (uint32_t)ctx->gpr[3]);
            { uint32_t r31 = (uint32_t)ctx->gpr[31]; fprintf(stderr, "      fmt-ctx r31=0x%08X:", r31);
              for (int o = 0; o <= 0x2C; o += 4) fprintf(stderr, " +%X=%08X", o, vm_read32(r31 + o)); fprintf(stderr, "\n"); }
#ifdef _WIN32
            vm_dump_guest_caller(c);
#endif
        }
    }
    static int dumped = 0;
    if (dumped < 3) {
        dumped++;
#ifdef _WIN32
        vm_dump_guest_caller((uint32_t)ctx->ctr);   /* symbolized guest caller chain */
#endif
        fprintf(stderr, "      lr=0x%08X r2=0x%08X r3=0x%08X r11=0x%08X r12=0x%08X\n",
                (uint32_t)ctx->lr, (uint32_t)ctx->gpr[2], (uint32_t)ctx->gpr[3],
                (uint32_t)ctx->gpr[11], (uint32_t)ctx->gpr[12]);
        for (int r = 0; r < 32; r += 8)
            fprintf(stderr, "      r%-2d: %08X %08X %08X %08X %08X %08X %08X %08X\n", r,
                (uint32_t)ctx->gpr[r+0],(uint32_t)ctx->gpr[r+1],(uint32_t)ctx->gpr[r+2],(uint32_t)ctx->gpr[r+3],
                (uint32_t)ctx->gpr[r+4],(uint32_t)ctx->gpr[r+5],(uint32_t)ctx->gpr[r+6],(uint32_t)ctx->gpr[r+7]);
    }
}

/* bctrl (real call): enforce callee-saved ABI. */
extern "C" void ps3_indirect_call(ppu_context* ctx) { ps3_ind_impl(ctx, true); }
/* bctr (computed jump / tail / switch-case): target shares the frame, no restore. */
extern "C" void ps3_indirect_jump(ppu_context* ctx) { ps3_ind_impl(ctx, false); }

/* Called when lifted code branches to a function that wasn't in this lift
 * (subset/incremental builds). Logs the first few; returns so execution can
 * continue (the result is undefined, but it won't crash the link). */
extern "C" void ppu_unlifted_stub(uint64_t addr, ppu_context* ctx)
{
    (void)ctx;
    static int logged = 0;
    if (logged < 20) {
        fprintf(stderr, "[ppu] call to unlifted function 0x%08X\n", (uint32_t)addr);
        logged++;
    }
}

/* The real lv2 syscall table (runtime/syscalls/lv2_register.c). */
extern "C" int lv2_try_syscall(ppu_context* ctx);

/* lv2 syscall dispatch: r11 = syscall number, args in r3.. (PPC ABI).
 * A few syscalls the CRT needs at boot are handled inline (boot-tuned); the
 * rest are dispatched to the real lv2 table, and only genuinely-unregistered
 * numbers fall through to the return-CELL_OK stub. */
extern "C" void lv2_syscall(ppu_context* ctx)
{
    uint64_t num = ctx->gpr[11];
    switch (num) {
    case 352: {   /* sys_memory_get_user_memory_size(sys_memory_info_t* info)
                   * info = { u32 total_user_memory; u32 available_user_memory }
                   * Values matched to RPCS3 ground truth for UC3: Total=0xD500000
                   * (213 MB user), Avail≈0x800000 (8 MB). The game polls this in a
                   * loop (from 0x001ffca4); the old 256/192 MB were wrong and made
                   * the game's memory-budget logic diverge. */
        uint32_t info = (uint32_t)ctx->gpr[3];
        uint64_t avail = (g_user_allocated < g_user_total)
                         ? (g_user_total - g_user_allocated) : 0x100000ull;
        avail &= ~0xFFFFull;   /* round down to 64 KB like the lv2 allocator */
        if (info) { vm_write32(info + 0, (uint32_t)g_user_total);
                    vm_write32(info + 4, (uint32_t)avail); }
        static int n = 0;
        if (n < 12) { fprintf(stderr, "[mem352] alloc=0x%llX avail=0x%llX (total=0x%llX)\n",
                              (unsigned long long)g_user_allocated, (unsigned long long)avail,
                              (unsigned long long)g_user_total); n++; }
        ctx->gpr[3] = 0;
        return;
    }
    case 330: {   /* sys_mmapper_allocate_address(u64 size, u64 flags,
                   * u64 alignment, u32* alloc_addr) -> reserve guest VA range */
        static uint32_t s_next_va = 0x11000000u;   /* just past the loaded image */
        uint32_t size  = (uint32_t)ctx->gpr[3];
        uint32_t align = (uint32_t)ctx->gpr[5];
        uint32_t out   = (uint32_t)ctx->gpr[6];
        if (align < 0x100000u) align = 0x100000u;   /* 1 MB min */
        s_next_va = (s_next_va + align - 1) & ~(align - 1);
        uint32_t va = s_next_va;
        s_next_va += (size + 0xFFFFFu) & ~0xFFFFFu;
        if (out) vm_write32(out, va);
        ctx->gpr[3] = 0;
        return;
    }
    case 403: {   /* sys_tty_write(s32 ch, cptr buf, u32 len, ptr pwritelen) */
        uint32_t ch   = (uint32_t)ctx->gpr[3];
        uint32_t buf  = (uint32_t)ctx->gpr[4];
        uint32_t len  = (uint32_t)ctx->gpr[5];
        uint32_t pwl  = (uint32_t)ctx->gpr[6];
        uint32_t wlen = len;
        static int oom_dumped = 0;
        static const char oom_prefix[] = "Out of memory in allocator";
        if (!oom_dumped && buf && len >= sizeof(oom_prefix) - 1 &&
            (!ppu_vm_size || (uint64_t)buf + sizeof(oom_prefix) - 1 <= ppu_vm_size) &&
            memcmp(vm_base + buf, oom_prefix, sizeof(oom_prefix) - 1) == 0) {
            oom_dumped = 1;
            fprintf(stderr, "[allocator-oom] first formatted failure, guest caller:\n");
            vm_dump_guest_caller(0);
        }
        /* Level-load failure probe: dump the guest caller (the level-lookup fn)
         * the first time the "no level definition" message is printed, to trace
         * why the level-definition registry is empty / world-test fallback. */
        static int lvl_dumped = 0;
        if (!lvl_dumped && buf && len >= 12 && len < 0x4000u &&
            (!ppu_vm_size || (uint64_t)buf + len <= ppu_vm_size)) {
            const char* p = (const char*)(vm_base + buf);
            for (uint32_t i = 0; i + 11 < len; i++) {
                if (memcmp(p + i, "no level def", 12) == 0) {
                    lvl_dumped = 1;
                    fprintf(stderr, "[level-fail] '%.*s' guest caller:\n", (int)(len < 80 ? len : 80), p);
                    vm_dump_guest_caller(0);
                    break;
                }
            }
        }
        if (wlen > 0x4000u) {   /* guard against garbage len (divergence dumps memory) */
            static int n = 0;
            if (n < 20) { fprintf(stderr, "[tty] suspicious len=%u (buf=0x%08X) clamped\n", len, buf); n++; }
            wlen = 0x4000u;
        }
        FILE* out = stdout;   /* keep all TTY on stdout, clean of [ppu] logs */
        for (uint32_t i = 0; i < wlen; i++) {
            if (ppu_vm_size && buf + i >= ppu_vm_size) break;
            fputc(vm_read8(buf + i), out);
        }
        fflush(out);
        if (pwl) vm_write32(pwl, len);
        ctx->gpr[3] = 0;
        return;
    }
    default: {
        /* Consult the real lv2 syscall table (semaphore / mutex / cond /
         * rwlock / event / timer / memory / vm / fs / spu). Initialised by
         * lv2_init_syscalls() at boot. Unregistered numbers fall through to the
         * return-0 stub below (which is what got the CRT this far). */
        if (lv2_try_syscall(ctx))
            return;
        static int logged = 0;
        if (logged < 40) {
            fprintf(stderr, "[ppu] lv2_syscall %llu (stub) args: r3=0x%08X r4=0x%08X r5=0x%08X r6=0x%08X r7=0x%08X\n",
                    (unsigned long long)num,
                    (uint32_t)ctx->gpr[3], (uint32_t)ctx->gpr[4], (uint32_t)ctx->gpr[5],
                    (uint32_t)ctx->gpr[6], (uint32_t)ctx->gpr[7]);
            logged++;
        }
        ctx->gpr[3] = 0;   /* CELL_OK */
        return;
    }
    }
}

/* ---------------------------------------------------------------------------
 * Minimal big-endian ELF64 loader: copies PT_LOAD segments into vm_base at
 * their vaddrs and zero-fills BSS (memsz > filesz). Returns e_entry (an OPD
 * address) or 0 on error. Assumes vm_base is allocated large enough.
 * -----------------------------------------------------------------------*/
static uint16_t be16(const uint8_t* p) { return (uint16_t)((p[0] << 8) | p[1]); }
static uint32_t be32(const uint8_t* p) { return ((uint32_t)p[0] << 24) | (p[1] << 16) | (p[2] << 8) | p[3]; }
static uint64_t be64(const uint8_t* p) { return ((uint64_t)be32(p) << 32) | be32(p + 4); }

extern "C" uint32_t ppu_load_elf(const char* path)
{
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "[ppu] cannot open %s\n", path); return 0; }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t* file = (uint8_t*)malloc(sz);
    if (!file || fread(file, 1, sz, f) != (size_t)sz) { fclose(f); free(file); return 0; }
    fclose(f);

    if (sz < 64 || memcmp(file, "\x7F""ELF", 4) != 0 || file[4] != 2 /*ELFCLASS64*/ || file[5] != 2 /*MSB*/) {
        fprintf(stderr, "[ppu] not a 64-bit big-endian ELF\n"); free(file); return 0;
    }
    uint64_t fsz = (uint64_t)sz;
    uint32_t entry = (uint32_t)be64(file + 24);
    uint64_t phoff = be64(file + 32);
    uint16_t phentsize = be16(file + 54);
    uint16_t phnum = be16(file + 56);

    int loaded = 0;
    uint32_t prx_param_vaddr = 0;
    for (uint16_t i = 0; i < phnum; i++) {
        uint64_t ph_off = phoff + (uint64_t)i * phentsize;
        if (ph_off + 56 > fsz) break;   /* program header itself out of the file */
        const uint8_t* ph = file + ph_off;
        uint32_t p_type = be32(ph + 0);
        if (p_type == 0x60000002u /*PT_PRX_PARAM*/)
            prx_param_vaddr = (uint32_t)be64(ph + 16);   /* p_vaddr */
        if (p_type == 7 /*PT_TLS*/) {
            g_tls_vaddr  = (uint32_t)be64(ph + 16);  /* p_vaddr */
            g_tls_filesz = (uint32_t)be64(ph + 32);  /* p_filesz */
            g_tls_memsz  = (uint32_t)be64(ph + 40);  /* p_memsz */
            fprintf(stderr, "[ppu] PT_TLS vaddr=0x%08X filesz=0x%X memsz=0x%X\n",
                    g_tls_vaddr, g_tls_filesz, g_tls_memsz);
        }
        if (p_type != 1 /*PT_LOAD*/) continue;
        uint64_t p_offset = be64(ph + 8);
        uint64_t p_vaddr  = be64(ph + 16);
        uint64_t p_filesz = be64(ph + 32);
        uint64_t p_memsz  = be64(ph + 40);
        if (p_memsz == 0) continue;
        /* Bounds-check both ends before touching host memory: the source range
         * must lie inside the ELF file, and the destination range inside the
         * guest VM (ppu_vm_size==0 = unchecked, matching the vm accessors).
         * Skip malformed/oversized segments rather than overflowing the host. */
        if (p_offset > fsz || p_filesz > fsz || p_offset + p_filesz > fsz) {
            fprintf(stderr, "[ppu] segment %u file range 0x%llX+0x%llX exceeds ELF (0x%llX), skipped\n",
                    i, (unsigned long long)p_offset, (unsigned long long)p_filesz, (unsigned long long)fsz);
            continue;
        }
        if (ppu_vm_size && (p_vaddr > ppu_vm_size || p_memsz > ppu_vm_size ||
                            p_vaddr + p_memsz > ppu_vm_size)) {
            fprintf(stderr, "[ppu] segment %u vaddr 0x%llX+0x%llX exceeds VM (0x%llX), skipped\n",
                    i, (unsigned long long)p_vaddr, (unsigned long long)p_memsz,
                    (unsigned long long)ppu_vm_size);
            continue;
        }
        memcpy(vm_base + (uint32_t)p_vaddr, file + p_offset, (size_t)p_filesz);
        if (p_memsz > p_filesz)
            memset(vm_base + (uint32_t)p_vaddr + (uint32_t)p_filesz, 0, (size_t)(p_memsz - p_filesz));
        /* Seed user-memory accounting with the loaded image (code+data). The
         * game's budget check reads this back as total-available. */
        g_user_allocated += (p_memsz + 0xFFFFull) & ~0xFFFFull;
        loaded++;
    }
    free(file);
    fprintf(stderr, "[ppu] loaded %d PT_LOAD segments, entry OPD 0x%08X\n", loaded, entry);

    /* Build the firmware import map now that guest memory is populated. */
    ppu_resolve_imports(prx_param_vaddr);
    return entry;
}

/* Resolve an OPD descriptor {u32 func, u32 toc}. */
extern "C" int ppu_opd_resolve(uint32_t opd, uint32_t* code, uint32_t* toc)
{
    uint32_t c = vm_read32(opd);
    uint32_t t = vm_read32(opd + 4);
    if (code) *code = c;
    if (toc)  *toc  = t;
    return c != 0;
}

/* Run from an entry OPD: set up r1 (stack) + r2 (TOC) and dispatch the entry
 * code address. Returns 0 if it ran, -1 if the entry function isn't registered. */
/* PPU worker-thread entry trampoline. sys_ppu_thread_create spawns a host
 * thread whose ctx has cia=entry (an OPD addr), gpr[3]=arg, stack + toc set; it
 * then calls g_ppu_thread_entry_trampoline(&ctx). Without this wired up the
 * worker threads were no-ops, so locks they should release stayed held and the
 * main thread spun forever (func_0092A170). Dispatch the guest entry like
 * ppu_run does, then drain the per-thread trampoline chain. */
extern "C" void ppu_thread_entry_trampoline_impl(ppu_context* ctx)
{
    uint32_t entry = (uint32_t)ctx->cia;
    uint32_t code = 0, toc = 0;
    ppu_opd_resolve(entry, &code, &toc);
    ppu_fn fn = ppu_lookup(code);
    if (!fn) { fn = ppu_lookup(entry); code = entry; }   /* entry may be raw code */
    if (!fn) { fprintf(stderr, "[thread] entry 0x%08X unresolved — no-op\n", entry); return; }
    if (g_canonical_toc) ctx->gpr[2] = g_canonical_toc;
    fn(ctx);
    while (g_trampoline_fn) {
        ctx->gpr[2] = g_canonical_toc;
        void (*tf)(void*) = g_trampoline_fn; g_trampoline_fn = 0; tf(ctx);
    }
}
extern "C" { extern void (*g_ppu_thread_entry_trampoline)(ppu_context* ctx); }

extern "C" int ppu_run(uint32_t entry_opd, uint32_t stack_top)
{
    g_ppu_thread_entry_trampoline = ppu_thread_entry_trampoline_impl;
    uint32_t code = 0, toc = 0;
    ppu_opd_resolve(entry_opd, &code, &toc);
    ppu_fn fn = ppu_lookup(code);
    if (!fn) { fprintf(stderr, "[ppu] entry code 0x%08X not registered\n", code); return -1; }

    g_canonical_toc = toc;    /* single-TOC binary: r2 is constant program-wide */

#ifdef _WIN32
    /* On a host access violation in lifted code, name the faulting guest
     * function (via the .pdb) before dying — turns a silent segfault into an
     * actionable "crashed in func_XXXX" line. */
    SetUnhandledExceptionFilter([](EXCEPTION_POINTERS* ep) -> LONG {
        fprintf(stderr, "\n[crash] exception 0x%08lX at host 0x%p\n",
                ep->ExceptionRecord->ExceptionCode, ep->ExceptionRecord->ExceptionAddress);
        ppu_tramp_dump();   /* dump the trampoline ring FIRST (before heavier DbgHelp work) */
        fflush(stderr);
        if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
            uintptr_t fault = (uintptr_t)ep->ExceptionRecord->ExceptionInformation[1];
            fprintf(stderr, "[crash] %s 0x%llX\n",
                    ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read",
                    (unsigned long long)fault);
            uintptr_t base = (uintptr_t)vm_base;
            if (base && fault >= base && fault - base < 0x100000000ull)
                fprintf(stderr, "[crash] guest address 0x%08llX (vm_base=%p)\n",
                        (unsigned long long)(fault - base), (void*)vm_base);
        }
        HANDLE proc = GetCurrentProcess();
        SymInitialize(proc, NULL, TRUE);
        char sbuf[sizeof(SYMBOL_INFO) + 256];
        SYMBOL_INFO* sym = (SYMBOL_INFO*)sbuf;
        sym->SizeOfStruct = sizeof(SYMBOL_INFO); sym->MaxNameLen = 255;
        DWORD64 disp = 0;
        if (SymFromAddr(proc, (DWORD64)(uintptr_t)ep->ExceptionRecord->ExceptionAddress, &disp, sym))
            fprintf(stderr, "[crash] in %s +0x%llX\n", sym->Name, (unsigned long long)disp);
        vm_dump_guest_caller(0);
        fflush(stderr);
        return EXCEPTION_EXECUTE_HANDLER;
    });
#endif

    ppu_context ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.gpr[1] = stack_top;   /* stack pointer */
    ctx.gpr[2] = toc;         /* TOC base (r2) */

    /* CellOS enters the process CRT with a valid argc/argv block. Several
     * retail CRTs compact the 64-bit launch vectors to 32-bit guest pointers
     * before calling main and assume argv[0] exists. Supplying zeroed r3-r6
     * made them read argv+4 at guest address 4 and overwrite address 0. Keep
     * the launch block just above the downward-growing stack. */
    uint32_t launch = stack_top + 0x1000u;
    uint32_t argv = launch;
    uint32_t envp = launch + 0x20u;
    uint32_t arg0 = launch + 0x40u;
    static const char process_name[] = "EBOOT.BIN";
    memcpy(vm_base + arg0, process_name, sizeof(process_name));
    vm_write64(argv + 0x00, arg0);
    vm_write64(argv + 0x08, 0);
    vm_write64(envp + 0x00, 0);
    ctx.gpr[3] = 1;           /* argc */
    ctx.gpr[4] = argv;
    ctx.gpr[5] = envp;
    ctx.gpr[6] = 0;           /* envc */
    fprintf(stderr, "[ppu] run: code 0x%08X, toc 0x%08X, sp 0x%08X\n", code, toc, stack_top);
    ppu_start_heartbeat();
    fn(&ctx);
    while (g_trampoline_fn) {
        ctx.gpr[2] = g_canonical_toc;   /* single-TOC: r2 is always the TOC */
        void (*tf)(void*) = g_trampoline_fn; g_trampoline_fn = 0; tf(&ctx);
    }
    return 0;
}
