/* Auto-generated by ppu_lifter.py -- do not edit by hand. */
#include "ppu_recomp.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

/* MSVC compatibility helpers */
#ifdef _MSC_VER
#include <intrin.h>
/* clang-cl defines _MSC_VER but provides __builtin_clz/clzll natively, so
 * redefining them is a hard error there -- only polyfill for real MSVC. */
#ifndef __clang__
static inline int __builtin_clz(unsigned int x) {
    unsigned long idx;
    _BitScanReverse(&idx, x);
    return 31 - (int)idx;
}
static inline int __builtin_clzll(unsigned long long x) {
    unsigned long idx;
    _BitScanReverse64(&idx, x);
    return 63 - (int)idx;
}
#endif
static inline int64_t ppc_mulhd(int64_t a, int64_t b) {
    int64_t hi;
    _mul128(a, b, &hi);
    return hi;
}
static inline uint64_t ppc_mulhdu(uint64_t a, uint64_t b) {
    uint64_t hi;
    _umul128(a, b, &hi);
    return hi;
}
#else
static inline int64_t ppc_mulhd(int64_t a, int64_t b) {
    return (int64_t)((__int128)(int64_t)a * (__int128)(int64_t)b >> 64);
}
static inline uint64_t ppc_mulhdu(uint64_t a, uint64_t b) {
    return (uint64_t)((unsigned __int128)a * (unsigned __int128)b >> 64);
}
#endif

/* VM base pointer (defined by game project) */
extern "C" uint8_t* vm_base;

/* Indirect call dispatch (bctrl/bctr) — implemented by the game project.
 * Looks up the guest address in CTR via a hash table and calls the
 * corresponding host function. Handles OPD resolution. */
extern "C" void ps3_indirect_call(ppu_context* ctx);
extern "C" void ps3_indirect_jump(ppu_context* ctx);

/* Trampoline function pointer for cross-fragment branches (TLS).
 * Must match the __declspec(thread) definition in indirect_dispatch. */
extern "C" __declspec(thread) void (*g_trampoline_fn)(void*);

/* Canonical TOC (r2) of this single-TOC static binary (defined in the runtime).
 * r2 is reserved for the TOC, so any drift to 0/garbage is a lost-TOC bug; the
 * trampoline drain restores it before each tail call. */
extern "C" unsigned int g_canonical_toc;

/* Drain pending trampolines after any call that might set g_trampoline_fn.
 * Converts cross-fragment fallthrough chains into iterative loops, and forces
 * r2 back to the canonical TOC at each hop. */
extern "C" void ppu_tramp_rec(void*);
#define DRAIN_TRAMPOLINE(ctx) do { \
    while (g_trampoline_fn) { \
        void(*_tf)(void*) = g_trampoline_fn; \
        g_trampoline_fn = 0; \
        ppu_tramp_rec((void*)_tf); \
        (ctx)->gpr[2] = g_canonical_toc; \
        _tf((void*)(ctx)); \
    } \
} while(0)

/* Guest call-depth guard. Incomplete HLE leaves engine structures half-built
 * during bring-up, which turns some recursive descents (tree/visitor walks)
 * into runaway recursion that exhausts the host stack / memory. Bounding the
 * per-thread guest call depth lets such a cycle unwind (the offending init step
 * is left incomplete) instead of crashing the whole run. */

/* Rotate helpers */
static inline uint32_t ppc_rlwinm(uint32_t rs, int sh, int mb, int me) {
    uint32_t rotated = (rs << sh) | (rs >> (32 - sh));
    uint32_t mask;
    if (mb <= me) {
        mask = ((uint32_t)-1 >> mb) & ((uint32_t)-1 << (31 - me));
    } else {
        mask = ((uint32_t)-1 >> mb) | ((uint32_t)-1 << (31 - me));
    }
    return rotated & mask;
}

static inline uint32_t ppc_rlwimi(uint32_t ra, uint32_t rs, int sh, int mb, int me) {
    uint32_t rotated = (rs << sh) | (rs >> (32 - sh));
    uint32_t mask;
    if (mb <= me) {
        mask = ((uint32_t)-1 >> mb) & ((uint32_t)-1 << (31 - me));
    } else {
        mask = ((uint32_t)-1 >> mb) | ((uint32_t)-1 << (31 - me));
    }
    return (rotated & mask) | (ra & ~mask);
}

/* 64-bit rotate helpers */
static inline uint64_t ppc_rotl64(uint64_t v, int n) {
    n &= 63;
    return (v << n) | (v >> (64 - n));
}
static inline uint64_t ppc_mask64(int mb, int me) {
    uint64_t mask;
    if (mb <= me) {
        mask = (mb == 0) ? ~0ULL : (~0ULL >> mb);
        mask &= (me == 63) ? ~0ULL : (~0ULL << (63 - me));
    } else {
        mask = (~0ULL >> mb) | (~0ULL << (63 - me));
    }
    return mask;
}
static inline uint64_t ppc_rldicl(uint64_t rs, int sh, int mb) {
    return ppc_rotl64(rs, sh) & ppc_mask64(mb, 63);
}
static inline uint64_t ppc_rldicr(uint64_t rs, int sh, int me) {
    return ppc_rotl64(rs, sh) & ppc_mask64(0, me);
}
static inline uint64_t ppc_rldic(uint64_t rs, int sh, int mb) {
    int me = 63 - sh;
    return ppc_rotl64(rs, sh) & ppc_mask64(mb, me);
}
static inline uint64_t ppc_rldimi(uint64_t ra, uint64_t rs, int sh, int mb) {
    int me = 63 - sh;
    uint64_t mask = ppc_mask64(mb, me);
    return (ppc_rotl64(rs, sh) & mask) | (ra & ~mask);
}

void func_010164C0(ppu_context* ctx) {
        ctx->gpr[0] = (int64_t)(int32_t)((int32_t)ctx->gpr[20] * 0x2917);
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[9] + 0x6918); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        if ((!((ctx->cr >> 28) & 8))) goto loc_010164DC;
        ctx->gpr[13] = (int64_t)(int32_t)(0x817 - (int32_t)ctx->gpr[0]);
        ctx->gpr[13] = (int64_t)(int32_t)(0x895 - (int32_t)ctx->gpr[0]);
        ctx->gpr[0] = (int64_t)(int32_t)((int32_t)ctx->gpr[20] * 0xC16);
        ctx->gpr[29] = (int64_t)(int32_t)(ctx->gpr[31] + ((uint32_t)0xB14 << 16));
loc_010164DC:
        ctx->gpr[31] = (int64_t)(int32_t)(ctx->gpr[1] + ((uint32_t)0xA13 << 16));
        ctx->gpr[13] = (int64_t)(int32_t)(0x913 - (int32_t)ctx->gpr[0]);
        ctx->gpr[13] = (int64_t)(int32_t)(0x9E0 - (int32_t)ctx->gpr[0]);
        ctx->gpr[13] = (int64_t)(int32_t)(0xA57 - (int32_t)ctx->gpr[0]);
        ctx->gpr[13] = (int64_t)(int32_t)(0xAE2 - (int32_t)ctx->gpr[0]);
        if (/* cond: bdnzgela */ 1) { g_trampoline_fn = (void(*)(void*))func_0000007C; return; }
        ctx->gpr[19] = (int64_t)(int32_t)(ctx->gpr[31] + -17024);
        /* TODO: .word 0x04000484 */;
        ctx->gpr[31] = (int64_t)(int32_t)((uint32_t)0x505 << 16);
        /* TODO: .word 0x04000406 */;
        ctx->gpr[31] = (int64_t)(int32_t)((uint32_t)0x2E83 << 16);
        if ((!((ctx->cr >> 28) & 8))) { g_trampoline_fn = (void(*)(void*))func_00000004; return; }
        ctx->gpr[25] = (int64_t)(int32_t)(ctx->gpr[9] + -8320);
        ctx->gpr[19] = (int64_t)(int32_t)(ctx->gpr[31] + -25600);
        /* TODO: .word 0x00200000 */;
        ctx->gpr[29] = (int64_t)(int32_t)(ctx->gpr[23] + 0x610C);
        /* TODO: .word 0x24FF40D2 */;
        /* TODO: .word 0x04000452 */;
        /* TODO: .word 0x24FE80D5 */;
        /* TODO: .word 0x040001D5 */;
        /* TODO: .word 0x24FE40D6 */;
        /* TODO: .word 0x04000256 */;
        /* TODO: .word 0x24FE00D7 */;
        /* TODO: .word 0x040002D7 */;
        /* TODO: .word 0x24FDC0D8 */;
        /* TODO: .word 0x04000358 */;
        /* TODO: .word 0x24FD80D9 */;
        /* TODO: .word 0x040004D9 */;
        /* TODO: .word 0x24FD40DA */;
        /* TODO: .word 0x040003DA */;
        /* TODO: .word 0x24004080 */;
        ctx->gpr[12] = (int64_t)(int32_t)(ctx->gpr[16] + 0); { int64_t _r = (int64_t)ctx->gpr[12]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        /* TODO: .word 0x24FFC0D0 */;
        /* TODO: .word 0x24FF80D1 */;
        /* TODO: .word 0x24FF00D3 */;
        /* TODO: .word 0x24FEC0D4 */;
        /* TODO: .word 0x24FA8081 */;
        ctx->gpr[5] = (int64_t)(int32_t)((int32_t)ctx->gpr[8] * 0x81);
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + 0x4603); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + -14844); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        /* TODO: .word 0x0400018B */;
        /* TODO: .word 0x5800C202 */;
        { g_trampoline_fn = (void(*)(void*))func_01016584; return; }
}

void func_0102E6F0(ppu_context* ctx) {
        ctx->gpr[28] = (int64_t)(int32_t)(ctx->gpr[7] + 0x2605);
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + -32108); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + 0x4284); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        ctx->gpr[7] = (int64_t)(int32_t)((int32_t)ctx->gpr[31] * 0xA13);
        ctx->gpr[0] = (int64_t)(int32_t)((int32_t)ctx->gpr[1] * 0x203);
        ctx->gpr[22] = (int64_t)(int32_t)((uint32_t)0x206 << 16);
        /* TODO: .word 0x5804C209 */;
        ctx->gpr[8] = (int64_t)(int32_t)(0x389 - (int32_t)ctx->gpr[0]);
        if (((ctx->ctr = (uint32_t)(ctx->ctr - 1)) != 0)) { g_trampoline_fn = (void(*)(void*))func_FFFFF814; return; }
        /* TODO: vmx_x905 v19, v31, v31 */;
        /* TODO: .word 0x24004283 */;
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + 0x216); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        vm_write16(ctx->gpr[5] + -0x747A, ctx->gpr[21]);
        /* TODO: .word 0x24000215 */;
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + 0x6899); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + 0x2885); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        /* trap: tdi 0, r6, 17104 — ignored */;
        /* TODO: .word 0x1403E818 */;
        ctx->gpr[11] = (int64_t)(int32_t)(-2280 - (int32_t)ctx->gpr[31]);
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + -22244); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        ctx->gpr[0] = (int64_t)(int32_t)(ctx->gpr[0] + 0x2904); { int64_t _r = (int64_t)ctx->gpr[0]; uint32_t _c = (_r < 0) ? 8u : (_r > 0) ? 4u : 2u; _c |= (uint32_t)((ctx->xer >> 31) & 1u); ctx->cr = (ctx->cr & 0x0FFFFFFFu) | (_c << 28); }
        /* trap: tdi 0, r7, 539 — ignored */;
        if (/* cond: ba */ 1) { g_trampoline_fn = (void(*)(void*))func_0006E818; return; }
        { g_trampoline_fn = (void(*)(void*))func_0102E74C; return; }
}

