#!/usr/bin/env python3
"""Splice selected functions from a targeted PPU lift into an existing lift.

Both trees must be generated by ppu_lifter.py. This keeps targeted patches
reproducible without hand-editing ppu_recomp_*.cpp or regenerating a whole ELF.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


FUNC_START = re.compile(r"(?m)^void (func_[0-9A-Fa-f]{8})\(ppu_context\* ctx\) \{")
TERMINAL_TRAMPOLINE = re.compile(
    r"(?m)^(?P<line>\s*\{ g_trampoline_fn = \(void\(\*\)\(void\*\)\)"
    r"func_[0-9A-Fa-f]{8}; return; \})\r?\n\}\s*$"
)


def generated_sources(root: Path) -> list[Path]:
    files = sorted(root.glob("ppu_recomp*.cpp")) + sorted(root.glob("ppu_recomp*.c"))
    return [path for path in files if path.is_file()]


def function_block(
    text: str, name: str, remove_embedded_table: bool = False
) -> tuple[int, int, str] | None:
    match = re.search(
        rf"(?m)^void {re.escape(name)}\(ppu_context\* ctx\) \{{", text
    )
    if not match:
        return None
    next_match = FUNC_START.search(text, match.end())
    table_match = re.search(r"(?m)^/\* Function table \*/", text[match.end():])
    candidates = [len(text)]
    if next_match:
        candidates.append(next_match.start())
    if table_match:
        candidates.append(match.end() + table_match.start())
    end = min(candidates)
    if remove_embedded_table and table_match and next_match:
        table_start = match.end() + table_match.start()
        if table_start < next_match.start():
            end = next_match.start()
    return match.start(), end, text[match.start():end]


def read_generated(path: Path) -> tuple[str, str]:
    raw = path.read_bytes()
    try:
        return raw.decode("utf-8"), "utf-8"
    except UnicodeDecodeError:
        return raw.decode("cp1252"), "cp1252"


def find_unique(
    root: Path, name: str, remove_embedded_table: bool = False
) -> tuple[Path, str, str, int, int, str]:
    matches: list[tuple[Path, str, str, int, int, str]] = []
    for path in generated_sources(root):
        text, encoding = read_generated(path)
        block = function_block(text, name, remove_embedded_table)
        if block:
            start, end, body = block
            matches.append((path, text, encoding, start, end, body))
    if len(matches) != 1:
        raise RuntimeError(f"{name}: expected one definition in {root}, found {len(matches)}")
    return matches[0]


def parse_function(value: str) -> str:
    address = int(value, 0)
    if not 0 <= address <= 0xFFFFFFFF:
        raise argparse.ArgumentTypeError("function address must fit in 32 bits")
    return f"func_{address:08X}"


def preserve_terminal_trampoline(source_body: str, dest_body: str) -> str:
    """Keep a destination fallthrough edge omitted by a one-function lift."""
    if TERMINAL_TRAMPOLINE.search(source_body):
        return source_body
    match = TERMINAL_TRAMPOLINE.search(dest_body)
    if not match:
        return source_body
    closing = re.search(r"(?m)^\}\s*$", source_body)
    if not closing:
        return source_body
    return source_body[:closing.start()] + match.group("line") + "\n" + source_body[closing.start():]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True, help="targeted lift directory")
    parser.add_argument("--dest", type=Path, required=True, help="existing generated tree")
    parser.add_argument(
        "--function", type=parse_function, action="append", required=True,
        help="guest function address to splice (repeatable)",
    )
    args = parser.parse_args()

    pending: dict[Path, tuple[str, str, list[tuple[int, int, str, str]]]] = {}
    for name in args.function:
        _, _, _, _, _, source_body = find_unique(args.source, name)
        dest_path, dest_text, encoding, start, end, dest_body = find_unique(
            args.dest, name, remove_embedded_table=True
        )
        source_body = preserve_terminal_trampoline(source_body, dest_body)
        if "Auto-generated by ppu_lifter.py" not in dest_text[:256]:
            raise RuntimeError(f"refusing non-generated destination: {dest_path}")
        if dest_path not in pending:
            pending[dest_path] = (dest_text, encoding, [])
        pending[dest_path][2].append((start, end, source_body, name))
        status = "unchanged" if source_body == dest_body else "queued"
        print(f"{name}: {status} -> {dest_path}")

    for path, (text, encoding, edits) in pending.items():
        for start, end, body, _ in sorted(edits, reverse=True):
            text = text[:start] + body + text[end:]
        temp = path.with_suffix(path.suffix + ".tmp")
        temp.write_text(text, encoding=encoding, newline="")
        os.replace(temp, path)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
