/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_func_00004000(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x4058);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[22] = spu_ls_read128(ctx, 0x5110);
        ctx->gpr[23] = spu_il(68);
        ctx->gpr[21] = spu_ai(ctx->gpr[22], 68);
        ctx->gpr[20] = spu_ls_read128(ctx, ctx->gpr[22]._u32[0] + ctx->gpr[23]._u32[0]);
        ctx->gpr[19] = spu_rotqby(ctx->gpr[20], ctx->gpr[21]);
        ctx->gpr[0] = spu_splat_u32(0x4020); ctx->pc = ctx->gpr[19]._u32[0]; spu_indirect_branch(ctx);
        ctx->gpr[2] = spu_ila(0x4078);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[2] = spu_ila(0x4080);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        /* nop */;
        ctx->gpr[17] = spu_ls_read128(ctx, 0x5110);
        ctx->gpr[18] = spu_il(52);
        ctx->gpr[3] = spu_fsmbi(0x0);
        ctx->gpr[4] = spu_il(1);
        ctx->gpr[5] = spu_fsmbi(0x0);
        ctx->gpr[6] = spu_il(0);
        /* nop */;
        ctx->gpr[16] = spu_ai(ctx->gpr[17], 52);
        ctx->gpr[15] = spu_ls_read128(ctx, ctx->gpr[17]._u32[0] + ctx->gpr[18]._u32[0]);
        ctx->gpr[14] = spu_rotqby(ctx->gpr[15], ctx->gpr[16]);
        ctx->gpr[0] = spu_splat_u32(0x4060); ctx->pc = ctx->gpr[14]._u32[0]; spu_indirect_branch(ctx);
        ctx->gpr[80] = spu_ori(ctx->gpr[3], 0);
        /* nop */;
        ctx->gpr[2] = spu_ila(0x40C0);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[2] = spu_ila(0x40C8);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[9] = spu_ls_read128(ctx, 0x5110);
        ctx->gpr[13] = spu_il(60);
        ctx->gpr[8] = spu_ai(ctx->gpr[9], 60);
        ctx->gpr[6] = spu_ls_read128(ctx, ctx->gpr[9]._u32[0] + ctx->gpr[13]._u32[0]);
        ctx->gpr[5] = spu_rotqby(ctx->gpr[6], ctx->gpr[8]);
        ctx->gpr[0] = spu_splat_u32(0x4090); ctx->pc = ctx->gpr[5]._u32[0]; spu_indirect_branch(ctx);
        /* branch hint (ignored) */;
        ctx->gpr[81] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[2] = spu_ila(0x40F0);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[11] = spu_ila(0xFFFF);
        ctx->gpr[9] = spu_fsmbi(0x0);
        ctx->gpr[3] = spu_il(4);
        ctx->gpr[5] = spu_fsmbi(0x0);
        ctx->gpr[6] = spu_ai(ctx->gpr[1], 32);
        ctx->gpr[12] = spu_shlqbyi(ctx->gpr[80], 4);
        ctx->gpr[8] = spu_il(8);
        ctx->gpr[10] = spu_rotmi(ctx->gpr[12], 112);
        ctx->gpr[80] = spu_and(ctx->gpr[10], ctx->gpr[11]);
        ctx->gpr[80] = spu_shli(ctx->gpr[80], 2);
        ctx->gpr[4] = spu_ai(ctx->gpr[80], 4);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[3]._u32[0]);
        ctx->gpr[2] = spu_rotqby(ctx->gpr[7], ctx->gpr[4]);
        ctx->gpr[13] = spu_a(ctx->gpr[80], ctx->gpr[2]);
loc_000040D8:
        ctx->gpr[25] = spu_ai(ctx->gpr[9], 32);
        ctx->gpr[8] = spu_ai(ctx->gpr[8], -1);
        ctx->gpr[9] = spu_ai(ctx->gpr[9], 16);
        spu_ls_write128(ctx, ctx->gpr[25]._u32[0] + ctx->gpr[1]._u32[0], ctx->gpr[5]);
        if (ctx->gpr[8]._u32[0] != 0) goto loc_000040D8;
        /* branch hint (ignored) */;
        ctx->gpr[3] = spu_il(0);
        ctx->gpr[4] = spu_shlqbyi(ctx->gpr[5], 0);
        { ctx->pc = 0x40F8; spu_func_000040F8(ctx); return; }
}

void spu_func_00004040(spu_context* ctx) {
        ctx->gpr[4] = spu_il(1);
}

void spu_func_00004058(spu_context* ctx) {
        ctx->gpr[14] = spu_rotqby(ctx->gpr[15], ctx->gpr[16]);
}

void spu_func_00004078(spu_context* ctx) {
        ctx->gpr[9] = spu_ls_read128(ctx, 0x5110);
}

void spu_func_00004080(spu_context* ctx) {
        ctx->gpr[8] = spu_ai(ctx->gpr[9], 60);
}

void spu_func_000040B0(spu_context* ctx) {
        ctx->gpr[6] = spu_ai(ctx->gpr[1], 32);
}

void spu_func_000040C0(spu_context* ctx) {
        ctx->gpr[80] = spu_and(ctx->gpr[10], ctx->gpr[11]);
}

void spu_func_000040C8(spu_context* ctx) {
        ctx->gpr[4] = spu_ai(ctx->gpr[80], 4);
}

void spu_func_000040F0(spu_context* ctx) {
        ctx->gpr[3] = spu_il(0);
}

void spu_func_000040F8(spu_context* ctx) {
        ctx->gpr[2] = spu_il(8);
        /* nop */;
        /* nop */;
        /* nop */;
loc_00004108:
        ctx->gpr[2] = spu_ai(ctx->gpr[2], -1);
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[6]._u32[0], ctx->gpr[4]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        if (ctx->gpr[2]._u32[0] != 0) goto loc_00004108;
        ctx->gpr[62] = spu_il(24);
        ctx->gpr[56] = spu_cwd(ctx->gpr[80], 8);
        ctx->gpr[60] = spu_ai(ctx->gpr[80], 24);
        ctx->gpr[57] = spu_fsmbi(0x0);
        { ctx->pc = 0x4128; spu_func_00004128(ctx); return; }
}

void spu_func_00004128(spu_context* ctx) {
        ctx->gpr[61] = spu_ai(ctx->gpr[80], 51);
        ctx->gpr[59] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[62]._u32[0]);
        ctx->gpr[52] = spu_il(24);
        ctx->gpr[43] = spu_cwd(ctx->gpr[80], 12);
        ctx->gpr[18] = spu_andi(ctx->gpr[61], -16);
        ctx->gpr[44] = spu_fsmbi(0x0);
        ctx->gpr[51] = spu_il(28);
        ctx->gpr[32] = spu_cwd(ctx->gpr[80], 0);
        ctx->gpr[50] = spu_ai(ctx->gpr[80], 28);
        ctx->gpr[33] = spu_fsmbi(0x0);
        ctx->gpr[39] = spu_il(28);
        /* nop */;
        ctx->gpr[28] = spu_il(8);
        ctx->gpr[19] = spu_rotqby(ctx->gpr[59], ctx->gpr[60]);
        ctx->gpr[27] = spu_ai(ctx->gpr[80], 8);
        ctx->gpr[58] = spu_ceqi(ctx->gpr[19], 0);
        ctx->gpr[48] = spu_sf(ctx->gpr[19], ctx->gpr[18]);
        ctx->gpr[58] = spu_shufb(ctx->gpr[18], ctx->gpr[57], ctx->gpr[55]);
        ctx->gpr[56] = spu_selb(ctx->gpr[55], ctx->gpr[59], ctx->gpr[53]);
        spu_ls_write128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[52]._u32[0], ctx->gpr[53]);
        ctx->gpr[49] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[51]._u32[0]);
        ctx->gpr[47] = spu_rotqby(ctx->gpr[49], ctx->gpr[50]);
        ctx->gpr[46] = spu_a(ctx->gpr[48], ctx->gpr[47]);
        ctx->gpr[45] = spu_ceqi(ctx->gpr[47], 0);
        ctx->gpr[45] = spu_shufb(ctx->gpr[46], ctx->gpr[44], ctx->gpr[42]);
        ctx->gpr[43] = spu_selb(ctx->gpr[42], ctx->gpr[49], ctx->gpr[40]);
        spu_ls_write128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[39]._u32[0], ctx->gpr[40]);
        ctx->gpr[38] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + 0x20);
        ctx->gpr[36] = spu_rotqby(ctx->gpr[38], ctx->gpr[80]);
        ctx->gpr[35] = spu_a(ctx->gpr[48], ctx->gpr[36]);
        ctx->gpr[34] = spu_ceqi(ctx->gpr[36], 0);
        ctx->gpr[34] = spu_shufb(ctx->gpr[35], ctx->gpr[33], ctx->gpr[31]);
        ctx->gpr[32] = spu_selb(ctx->gpr[31], ctx->gpr[38], ctx->gpr[29]);
        spu_ls_write128(ctx, ctx->gpr[80]._u32[0] + 0x20, ctx->gpr[29]);
        ctx->gpr[26] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[28]._u32[0]);
        ctx->gpr[17] = spu_rotqby(ctx->gpr[26], ctx->gpr[27]);
        /* nop */;
        if (ctx->gpr[17]._u32[0] == 0) { ctx->pc = 0x42F0; spu_func_000042F0(ctx); return; }
        ctx->gpr[65] = spu_il(24);
        ctx->gpr[16] = spu_fsmbi(0x0);
        ctx->gpr[64] = spu_ai(ctx->gpr[80], 24);
        /* nop */;
        ctx->gpr[14] = spu_sf(ctx->gpr[19], ctx->gpr[18]);
        ctx->gpr[63] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[65]._u32[0]);
        /* nop */;
        ctx->gpr[11] = spu_rotqby(ctx->gpr[63], ctx->gpr[64]);
        ctx->gpr[6] = spu_il(4);
        ctx->gpr[21] = spu_cwd(ctx->gpr[11], 4);
        ctx->gpr[26] = spu_ai(ctx->gpr[11], 4);
        ctx->gpr[10] = spu_cwd(ctx->gpr[11], 12);
        ctx->gpr[12] = spu_il(12);
        ctx->gpr[25] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[6]._u32[0]);
        ctx->gpr[15] = spu_ai(ctx->gpr[11], 12);
        ctx->gpr[71] = spu_cwd(ctx->gpr[11], 8);
        { ctx->pc = 0x4200; spu_func_00004200(ctx); return; }
}

void spu_func_00004200(spu_context* ctx) {
        ctx->gpr[67] = spu_il(8);
        ctx->gpr[76] = spu_ai(ctx->gpr[11], 8);
        ctx->gpr[24] = spu_rotqby(ctx->gpr[25], ctx->gpr[26]);
        ctx->gpr[23] = spu_ceqi(ctx->gpr[24], 0);
        ctx->gpr[22] = spu_a(ctx->gpr[14], ctx->gpr[24]);
        ctx->gpr[20] = spu_andc(ctx->gpr[22], ctx->gpr[23]);
        ctx->gpr[21] = spu_selb(ctx->gpr[20], ctx->gpr[25], ctx->gpr[8]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[6]._u32[0], ctx->gpr[8]);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[12]._u32[0]);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[5], ctx->gpr[15]);
        ctx->gpr[7] = spu_ceqi(ctx->gpr[4], 0);
        ctx->gpr[2] = spu_a(ctx->gpr[14], ctx->gpr[4]);
        ctx->gpr[79] = spu_andc(ctx->gpr[2], ctx->gpr[7]);
        ctx->gpr[10] = spu_selb(ctx->gpr[79], ctx->gpr[5], ctx->gpr[77]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[12]._u32[0], ctx->gpr[77]);
        ctx->gpr[75] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[67]._u32[0]);
        ctx->gpr[74] = spu_rotqby(ctx->gpr[75], ctx->gpr[76]);
        ctx->gpr[73] = spu_ceqi(ctx->gpr[74], 0);
        ctx->gpr[72] = spu_a(ctx->gpr[14], ctx->gpr[74]);
        ctx->gpr[70] = spu_andc(ctx->gpr[72], ctx->gpr[73]);
        ctx->gpr[71] = spu_selb(ctx->gpr[70], ctx->gpr[75], ctx->gpr[68]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[67]._u32[0], ctx->gpr[68]);
        ctx->gpr[66] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotqby(ctx->gpr[66], ctx->gpr[11]);
        /* nop */;
        if (ctx->gpr[3]._u32[0] == 0) { ctx->pc = 0x42E0; spu_func_000042E0(ctx); return; }
        ctx->gpr[28] = spu_ceqi(ctx->gpr[3], 0);
        /* branch hint (ignored) */;
        ctx->gpr[30] = spu_ai(ctx->gpr[3], -1);
        ctx->gpr[27] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[12]._u32[0]);
        ctx->gpr[29] = spu_il(0);
        ctx->gpr[5] = spu_fsmbi(0x0);
        ctx->gpr[28] = spu_shufb(ctx->gpr[30], ctx->gpr[29], ctx->gpr[12]);
        ctx->gpr[6] = spu_ai(ctx->gpr[12], 1);
        /* nop */;
        ctx->gpr[7] = spu_rotqby(ctx->gpr[27], ctx->gpr[15]);
        ctx->gpr[39] = spu_il(8);
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[7]._u32[0]);
        ctx->gpr[38] = spu_ai(ctx->gpr[11], 8);
        ctx->gpr[42] = spu_cwx(ctx->gpr[5], ctx->gpr[7]);
        ctx->gpr[6] = spu_ai(ctx->gpr[6], -1);
        ctx->gpr[42] = spu_selb(ctx->gpr[13], ctx->gpr[41], ctx->gpr[40]);
        spu_ls_write128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[7]._u32[0], ctx->gpr[40]);
        ctx->gpr[37] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[39]._u32[0]);
        { ctx->pc = 0x42B0; spu_func_000042B0(ctx); return; }
}

void spu_func_000042B0(spu_context* ctx) {
        /* nop */;
        ctx->gpr[36] = spu_rotqby(ctx->gpr[37], ctx->gpr[38]);
        ctx->gpr[35] = spu_a(ctx->gpr[5], ctx->gpr[36]);
        ctx->gpr[34] = spu_ls_read128(ctx, ctx->gpr[5]._u32[0] + ctx->gpr[36]._u32[0]);
        ctx->gpr[5] = spu_ai(ctx->gpr[5], 4);
        ctx->gpr[33] = spu_rotqby(ctx->gpr[34], ctx->gpr[35]);
        ctx->gpr[32] = spu_shli(ctx->gpr[33], 2);
        ctx->gpr[31] = spu_ai(ctx->gpr[32], 15);
        ctx->gpr[15] = spu_andi(ctx->gpr[31], -16);
        /* nop */;
        ctx->gpr[13] = spu_a(ctx->gpr[13], ctx->gpr[15]);
        if (ctx->gpr[6]._u32[0] != 0) { ctx->pc = 0x4290; spu_func_00004290(ctx); return; }
        ctx->gpr[16] = spu_ai(ctx->gpr[16], 1);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 16);
        ctx->gpr[43] = spu_clgt(ctx->gpr[17], ctx->gpr[16]);
        if (ctx->gpr[43]._u32[0] != 0) { ctx->pc = 0x41E0; spu_func_000041E0(ctx); return; }
        ctx->gpr[44] = spu_il(12);
        /* branch hint (ignored) */;
        ctx->gpr[17] = spu_ai(ctx->gpr[80], 12);
        ctx->gpr[16] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[44]._u32[0]);
        { ctx->pc = 0x4300; spu_func_00004300(ctx); return; }
}

void spu_func_00004300(spu_context* ctx) {
        ctx->gpr[14] = spu_rotqby(ctx->gpr[16], ctx->gpr[17]);
        if (ctx->gpr[14]._u32[0] == 0) { ctx->pc = 0x43B4; spu_func_000043B4(ctx); return; }
        ctx->gpr[51] = spu_il(28);
        ctx->gpr[49] = spu_fsmbi(0x0);
        { ctx->pc = 0x4310; spu_func_00004310(ctx); return; }
}

void spu_func_00004310(spu_context* ctx) {
        ctx->gpr[48] = spu_ceqi(ctx->gpr[14], 0);
        /* nop */;
        ctx->gpr[50] = spu_ai(ctx->gpr[14], -1);
        ctx->gpr[45] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[51]._u32[0]);
        ctx->gpr[46] = spu_ai(ctx->gpr[80], 28);
        ctx->gpr[48] = spu_shufb(ctx->gpr[50], ctx->gpr[49], ctx->gpr[47]);
        ctx->gpr[12] = spu_sf(ctx->gpr[19], ctx->gpr[18]);
        ctx->gpr[14] = spu_ai(ctx->gpr[47], 1);
        ctx->gpr[11] = spu_rotqby(ctx->gpr[45], ctx->gpr[46]);
        goto loc_00004340;
        ctx->gpr[13] = spu_a(ctx->gpr[13], ctx->gpr[2]);
        /* nop */;
loc_00004340:
        ctx->gpr[14] = spu_ai(ctx->gpr[14], -1);
        ctx->gpr[74] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x20);
        ctx->gpr[65] = spu_cwd(ctx->gpr[1], 8);
        /* branch hint (ignored) */;
        ctx->gpr[68] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + 0x30);
        ctx->gpr[56] = spu_cwd(ctx->gpr[1], 12);
        { ctx->pc = 0x4358; spu_func_00004358(ctx); return; }
}

void spu_func_00004358(spu_context* ctx) {
        ctx->gpr[69] = spu_cwd(ctx->gpr[1], 0);
        ctx->gpr[70] = spu_rotqbyi(ctx->gpr[74], 8);
        { ctx->pc = 0x4360; spu_func_00004360(ctx); return; }
}

void spu_func_00004360(spu_context* ctx) {
        ctx->gpr[62] = spu_cwd(ctx->gpr[1], 4);
        ctx->gpr[72] = spu_ceqi(ctx->gpr[68], 0);
        ctx->gpr[67] = spu_ceqi(ctx->gpr[70], 0);
        ctx->gpr[66] = spu_a(ctx->gpr[12], ctx->gpr[70]);
        ctx->gpr[71] = spu_a(ctx->gpr[12], ctx->gpr[68]);
        ctx->gpr[64] = spu_andc(ctx->gpr[66], ctx->gpr[67]);
        ctx->gpr[3] = spu_andc(ctx->gpr[71], ctx->gpr[72]);
        ctx->gpr[65] = spu_selb(ctx->gpr[64], ctx->gpr[74], ctx->gpr[55]);
        ctx->gpr[69] = spu_selb(ctx->gpr[3], ctx->gpr[68], ctx->gpr[61]);
        ctx->gpr[59] = spu_rotqbyi(ctx->gpr[55], 12);
        ctx->gpr[62] = spu_selb(ctx->gpr[13], ctx->gpr[61], ctx->gpr[60]);
        ctx->gpr[58] = spu_ceqi(ctx->gpr[59], 0);
        ctx->gpr[57] = spu_a(ctx->gpr[12], ctx->gpr[59]);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x30, ctx->gpr[60]);
        ctx->gpr[54] = spu_andc(ctx->gpr[57], ctx->gpr[58]);
        ctx->gpr[56] = spu_selb(ctx->gpr[54], ctx->gpr[55], ctx->gpr[53]);
        ctx->gpr[52] = spu_rotqbyi(ctx->gpr[53], 4);
        spu_ls_write128(ctx, ctx->gpr[11]._u32[0] + 0x20, ctx->gpr[53]);
        ctx->gpr[11] = spu_ai(ctx->gpr[11], 64);
        ctx->gpr[2] = spu_shli(ctx->gpr[52], 4);
        if (ctx->gpr[14]._u32[0] != 0) { ctx->pc = 0x4338; spu_func_00004338(ctx); return; }
        ctx->gpr[13] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + 0x10);
        ctx->gpr[3] = spu_rotqby(ctx->gpr[13], ctx->gpr[80]);
        if (ctx->gpr[3]._u32[0] == 0) { ctx->pc = 0x4418; spu_func_00004418(ctx); return; }
        ctx->gpr[10] = spu_sf(ctx->gpr[19], ctx->gpr[18]);
        /* branch hint (ignored) */;
        ctx->gpr[76] = spu_ceqi(ctx->gpr[3], 0);
        ctx->gpr[75] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + 0x20);
        ctx->gpr[77] = spu_ai(ctx->gpr[3], -1);
        { ctx->pc = 0x43D4; spu_func_000043D4(ctx); return; }
}

void spu_func_000043D4(spu_context* ctx) {
        ctx->gpr[19] = spu_fsmbi(0x0);
        ctx->gpr[8] = spu_il(0);
        ctx->gpr[76] = spu_shufb(ctx->gpr[77], ctx->gpr[19], ctx->gpr[18]);
        ctx->gpr[9] = spu_rotqby(ctx->gpr[75], ctx->gpr[80]);
        ctx->gpr[7] = spu_ai(ctx->gpr[18], 1);
        ctx->gpr[78] = spu_a(ctx->gpr[8], ctx->gpr[9]);
        ctx->gpr[5] = spu_cwd(ctx->gpr[1], 0);
        ctx->gpr[7] = spu_ai(ctx->gpr[7], -1);
        /* nop */;
        ctx->gpr[8] = spu_ai(ctx->gpr[8], 96);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[78]._u32[0] + 0x50);
        ctx->gpr[20] = spu_ceqi(ctx->gpr[4], 0);
        ctx->gpr[6] = spu_a(ctx->gpr[10], ctx->gpr[4]);
        { ctx->pc = 0x4408; spu_func_00004408(ctx); return; }
}

void spu_func_00004408(spu_context* ctx) {
        ctx->gpr[2] = spu_andc(ctx->gpr[6], ctx->gpr[20]);
        ctx->gpr[5] = spu_selb(ctx->gpr[2], ctx->gpr[4], ctx->gpr[79]);
        spu_ls_write128(ctx, ctx->gpr[78]._u32[0] + 0x50, ctx->gpr[79]);
        if (ctx->gpr[7]._u32[0] != 0) { ctx->pc = 0x43E8; spu_func_000043E8(ctx); return; }
        ctx->gpr[3] = spu_ori(ctx->gpr[80], 0);
        /* nop */;
        ctx->gpr[4] = spu_ai(ctx->gpr[1], 32);
        ctx->gpr[0] = spu_splat_u32(0x4428); spu_func_00004598(ctx);
        ctx->gpr[29] = spu_il(20);
        ctx->gpr[12] = spu_ai(ctx->gpr[80], 20);
        ctx->gpr[28] = spu_clgti(ctx->gpr[81], 31);
        ctx->gpr[26] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + ctx->gpr[29]._u32[0]);
        { ctx->pc = 0x4438; spu_func_00004438(ctx); return; }
}

void spu_func_00004438(spu_context* ctx) {
        ctx->gpr[27] = spu_clgti(ctx->gpr[81], 7);
        ctx->gpr[7] = spu_nor(ctx->gpr[28], ctx->gpr[28]);
        ctx->gpr[8] = spu_sfi(ctx->gpr[27], 0);
        ctx->gpr[23] = spu_sfi(ctx->gpr[7], 0);
        ctx->gpr[4] = spu_rotqby(ctx->gpr[26], ctx->gpr[12]);
        ctx->gpr[25] = spu_andi(ctx->gpr[4], 15);
        ctx->gpr[24] = spu_ceqi(ctx->gpr[25], 0);
        ctx->gpr[22] = spu_sfi(ctx->gpr[24], 0);
        ctx->gpr[10] = spu_and(ctx->gpr[22], ctx->gpr[23]);
        ctx->gpr[80] = spu_and(ctx->gpr[10], ctx->gpr[8]);
        if (ctx->gpr[80]._u32[0] == 0) { ctx->pc = 0x453C; spu_func_0000453C(ctx); return; }
        ctx->gpr[15] = spu_rdch(ctx, SPU_RdMachStat);
        ctx->gpr[30] = spu_andi(ctx->gpr[15], 1);
        if (ctx->gpr[30]._u32[0] == 0) { ctx->pc = 0x4544; spu_func_00004544(ctx); return; }
        ctx->gpr[2] = spu_ila(0x44C8);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[36] = spu_il(128);
        ctx->gpr[34] = spu_il(32);
        ctx->gpr[38] = spu_ai(ctx->gpr[1], 32);
        { ctx->pc = 0x4484; spu_func_00004484(ctx); return; }
}

void spu_func_00004448(spu_context* ctx) {
        ctx->gpr[4] = spu_rotqby(ctx->gpr[26], ctx->gpr[12]);
}

void spu_func_00004484(spu_context* ctx) {
        ctx->gpr[37] = spu_shlqbyi(ctx->gpr[4], 0);
        ctx->gpr[35] = spu_ori(ctx->gpr[81], 0);
        spu_wrch(ctx, MFC_LSA, ctx->gpr[38]);
        { ctx->pc = 0x4490; spu_func_00004490(ctx); return; }
}

void spu_func_00004490(spu_context* ctx) {
        spu_wrch(ctx, MFC_EAL, ctx->gpr[37]);
        spu_wrch(ctx, MFC_Size, ctx->gpr[36]);
        spu_wrch(ctx, MFC_TagID, ctx->gpr[35]);
        spu_wrch(ctx, MFC_Cmd, ctx->gpr[34]);
        ctx->gpr[2] = spu_ila(0x44F8);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[33] = spu_il(1);
        ctx->gpr[4] = spu_shl(ctx->gpr[33], ctx->gpr[81]);
        ctx->gpr[32] = spu_ceqbi(ctx->gpr[4], 0);
        ctx->gpr[31] = spu_xsbh(ctx->gpr[32]);
        if (ctx->gpr[31]._u16[1] == 0) { ctx->pc = 0x454C; spu_func_0000454C(ctx); return; }
        ctx->gpr[5] = spu_ori(ctx->gpr[4], 0);
        /* branch hint (ignored) */;
        ctx->gpr[40] = spu_rdch(ctx, SPU_RdMachStat);
        ctx->gpr[39] = spu_andi(ctx->gpr[40], 1);
        if (ctx->gpr[39]._u32[0] == 0) { ctx->pc = 0x4534; spu_func_00004534(ctx); return; }
        ctx->gpr[2] = spu_ila(0x4528);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[43] = spu_il(1);
        spu_wrch(ctx, MFC_WrTagMask, ctx->gpr[5]);
        { ctx->pc = 0x44E0; spu_func_000044E0(ctx); return; }
}

void spu_func_000044C8(spu_context* ctx) {
        ctx->gpr[39] = spu_andi(ctx->gpr[40], 1);
}

void spu_func_000044E0(spu_context* ctx) {
        spu_wrch(ctx, MFC_WrTagUpdate, ctx->gpr[43]);
        ctx->gpr[42] = spu_rdch(ctx, MFC_RdTagStat);
        ctx->gpr[3] = spu_ila(0x4540);
        ctx->pc = ctx->gpr[3]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_func_000044F0(spu_context* ctx) {
        ctx->gpr[41] = spu_ceq(ctx->gpr[4], ctx->gpr[42]);
        if (ctx->gpr[41]._u32[0] == 0) { ctx->pc = 0x44C0; spu_func_000044C0(ctx); return; }
        ctx->gpr[2] = spu_ila(0x4550);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[46] = spu_ls_read128(ctx, 0x5110);
        ctx->gpr[3] = spu_ori(ctx->gpr[81], 0);
        ctx->gpr[45] = spu_ls_read128(ctx, ctx->gpr[46]._u32[0] + 0x40);
        ctx->gpr[81] = spu_rotqby(ctx->gpr[45], ctx->gpr[46]);
        /* nop */;
        ctx->gpr[0] = spu_splat_u32(0x4518); ctx->pc = ctx->gpr[81]._u32[0]; spu_indirect_branch(ctx);
        { ctx->pc = 0x4518; spu_func_00004518(ctx); return; }
}

void spu_func_000044F8(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x4550);
}

void spu_func_00004518(spu_context* ctx) {
        ctx->gpr[2] = spu_ila(0x4570);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0xD0);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 192);
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        return;
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        { ctx->pc = 0x44D0; spu_func_000044D0(ctx); return; }
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        { ctx->pc = 0x4464; spu_func_00004464(ctx); return; }
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        { ctx->pc = 0x4470; spu_func_00004470(ctx); return; }
        ctx->gpr[5] = spu_ori(ctx->gpr[4], 0);
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

void spu_func_00004528(spu_context* ctx) {
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
}

void spu_func_00004538(spu_context* ctx) {
        { ctx->pc = 0x44D0; spu_func_000044D0(ctx); return; }
}

void spu_func_00004540(spu_context* ctx) {
        { ctx->pc = 0x4464; spu_func_00004464(ctx); return; }
}

void spu_func_00004550(spu_context* ctx) {
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

void spu_func_00004554(spu_context* ctx) {
        ctx->gpr[16] = spu_rdch(ctx, SPU_RdMachStat);
}

void spu_func_0000455C(spu_context* ctx) {
        if (ctx->gpr[14]._u32[0] != 0) { ctx->pc = 0x4568; spu_func_00004568(ctx); return; }
}

void spu_func_00004564(spu_context* ctx) {
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

void spu_func_0000456C(spu_context* ctx) {
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
}

void spu_func_00004570(spu_context* ctx) {
        ctx->gpr[11] = spu_il(1);
}

void spu_func_00004588(spu_context* ctx) {
        ctx->gpr[17] = spu_ceq(ctx->gpr[4], ctx->gpr[44]);
        if (ctx->gpr[17]._u32[0] == 0) { ctx->pc = 0x4550; spu_func_00004550(ctx); return; }
        { ctx->pc = 0x44F8; spu_func_000044F8(ctx); return; }
        /* nop */;
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[85]);
        ctx->gpr[85] = spu_ori(ctx->gpr[3], 0);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[3]._u32[0] + 0x10);
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x140, ctx->gpr[99]);
        ctx->gpr[99] = spu_ori(ctx->gpr[4], 0);
}

void spu_func_000045B8(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        ctx->gpr[2] = spu_rotqby(ctx->gpr[3], ctx->gpr[85]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[83]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[84]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[86]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[87]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[89]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[90]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[91]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[92]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xE0, ctx->gpr[93]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[94]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x100, ctx->gpr[95]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x110, ctx->gpr[96]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x120, ctx->gpr[97]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x130, ctx->gpr[98]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x150, ctx->gpr[100]);
        /* branch hint (ignored) */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x170, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -368);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = 0x46C8; spu_func_000046C8(ctx); return; }
        ctx->gpr[98] = spu_il(0);
        ctx->gpr[93] = spu_ls_read128(ctx, 0x50B0);
        ctx->gpr[89] = spu_il(0);
        ctx->gpr[94] = spu_ls_read128(ctx, 0x50C0);
        ctx->gpr[90] = spu_ls_read128(ctx, 0x50D0);
        ctx->gpr[91] = spu_ls_read128(ctx, 0x50E0);
        /* nop */;
        ctx->gpr[92] = spu_ls_read128(ctx, 0x50F0);
        ctx->gpr[12] = spu_ai(ctx->gpr[89], 13);
        ctx->gpr[14] = spu_ls_read128(ctx, ctx->gpr[85]._u32[0] + 0x20);
        /* nop */;
        ctx->gpr[13] = spu_rotqby(ctx->gpr[14], ctx->gpr[85]);
        ctx->gpr[88] = spu_a(ctx->gpr[89], ctx->gpr[13]);
        ctx->gpr[11] = spu_ls_read128(ctx, ctx->gpr[89]._u32[0] + ctx->gpr[13]._u32[0]);
        ctx->gpr[10] = spu_rotqby(ctx->gpr[11], ctx->gpr[12]);
        ctx->gpr[9] = spu_andi(ctx->gpr[10], -128);
        { ctx->pc = 0x4658; spu_func_00004658(ctx); return; }
}

void spu_func_000045C0(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
}

void spu_func_000045D8(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[88]);
}

void spu_func_00004658(spu_context* ctx) {
        ctx->gpr[8] = spu_ceqbi(ctx->gpr[9], 0);
        ctx->gpr[6] = spu_nor(ctx->gpr[8], ctx->gpr[8]);
        ctx->gpr[4] = spu_xsbh(ctx->gpr[8]);
        ctx->gpr[5] = spu_fsm(ctx->gpr[6]);
        ctx->gpr[97] = spu_sfi(ctx->gpr[5], 0);
        if (ctx->gpr[4]._u16[1] != 0) { ctx->pc = 0x4730; spu_func_00004730(ctx); return; }
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x0);
        /* branch hint (ignored) */;
        ctx->gpr[9] = spu_rotqbyi(ctx->gpr[80], 8);
        if (ctx->gpr[9]._u32[0] == 0) { ctx->pc = 0x46B0; spu_func_000046B0(ctx); return; }
        ctx->gpr[95] = spu_ceqbi(ctx->gpr[97], 0);
        ctx->gpr[81] = spu_xsbh(ctx->gpr[95]);
        /* nop */;
        if (ctx->gpr[81]._u16[1] == 0) { ctx->pc = 0x4D10; spu_func_00004D10(ctx); return; }
        { ctx->pc = 0x4690; spu_func_00004690(ctx); return; }
}

void spu_func_00004690(spu_context* ctx) {
        ctx->gpr[97] = spu_ceqi(ctx->gpr[9], 0);
        ctx->gpr[100] = spu_fsmbi(0x0);
        ctx->gpr[96] = spu_ai(ctx->gpr[9], -1);
        ctx->gpr[97] = spu_shufb(ctx->gpr[96], ctx->gpr[100], ctx->gpr[88]);
        ctx->gpr[8] = spu_ai(ctx->gpr[88], 1);
loc_000046A4:
        ctx->gpr[8] = spu_ai(ctx->gpr[8], -1);
        /* nop */;
        if (ctx->gpr[8]._u32[0] != 0) goto loc_000046A4;
        ctx->gpr[98] = spu_ai(ctx->gpr[98], 1);
        ctx->gpr[65] = spu_ls_read128(ctx, ctx->gpr[85]._u32[0] + 0x10);
        ctx->gpr[89] = spu_ai(ctx->gpr[89], 96);
        ctx->gpr[10] = spu_rotqby(ctx->gpr[65], ctx->gpr[85]);
        ctx->gpr[68] = spu_clgt(ctx->gpr[10], ctx->gpr[98]);
        { ctx->pc = 0x46C4; spu_func_000046C4(ctx); return; }
}

void spu_func_000046C4(spu_context* ctx) {
        if (ctx->gpr[68]._u32[0] != 0) { ctx->pc = 0x4638; spu_func_00004638(ctx); return; }
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x180);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], 368);
        { ctx->pc = 0x46D0; spu_func_000046D0(ctx); return; }
}

void spu_func_000046D0(spu_context* ctx) {
        ctx->gpr[80] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x10);
        ctx->gpr[81] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x20);
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x30);
        /* branch hint (ignored) */;
        ctx->gpr[83] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x40);
        ctx->gpr[84] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x50);
        { ctx->pc = 0x46E8; spu_func_000046E8(ctx); return; }
}

void spu_func_000046E8(spu_context* ctx) {
        ctx->gpr[85] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x60);
        ctx->gpr[86] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x70);
        ctx->gpr[87] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x80);
        ctx->gpr[88] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x90);
        ctx->gpr[89] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xA0);
        ctx->gpr[90] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xB0);
        ctx->gpr[91] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xC0);
        ctx->gpr[92] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xD0);
        ctx->gpr[93] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xE0);
        ctx->gpr[94] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0xF0);
        ctx->gpr[95] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x100);
        ctx->gpr[96] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x110);
        ctx->gpr[97] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x120);
        ctx->gpr[98] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x130);
        /* branch hint (ignored) */;
        ctx->gpr[99] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x140);
        ctx->gpr[100] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + -0x150);
        return;
        ctx->gpr[21] = spu_il(8);
        ctx->gpr[19] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x30);
        ctx->gpr[16] = spu_ai(ctx->gpr[85], 8);
        ctx->gpr[20] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x40);
        ctx->gpr[18] = spu_ilhu(0x3F80);
        ctx->gpr[15] = spu_ls_read128(ctx, ctx->gpr[85]._u32[0] + ctx->gpr[21]._u32[0]);
        ctx->gpr[17] = spu_fsmbi(0xF);
        ctx->gpr[17] = spu_shufb(ctx->gpr[20], ctx->gpr[18], ctx->gpr[81]);
        { ctx->pc = 0x4750; spu_func_00004750(ctx); return; }
}

void spu_func_00004750(spu_context* ctx) {
        ctx->gpr[17] = spu_shufb(ctx->gpr[19], ctx->gpr[18], ctx->gpr[80]);
        ctx->gpr[6] = spu_rotqby(ctx->gpr[15], ctx->gpr[16]);
        /* nop */;
        if (ctx->gpr[6]._u32[0] == 0) { ctx->pc = 0x4670; spu_func_00004670(ctx); return; }
        ctx->gpr[96] = spu_il(0);
        ctx->gpr[100] = spu_fsmbi(0x0);
        ctx->gpr[29] = spu_il(24);
        /* branch hint (ignored) */;
        ctx->gpr[28] = spu_ai(ctx->gpr[85], 24);
        /* nop */;
        ctx->gpr[25] = spu_il(4);
        ctx->gpr[27] = spu_ls_read128(ctx, ctx->gpr[85]._u32[0] + ctx->gpr[29]._u32[0]);
        ctx->gpr[95] = spu_il(1);
        ctx->gpr[26] = spu_rotqby(ctx->gpr[27], ctx->gpr[28]);
        { ctx->pc = 0x4788; spu_func_00004788(ctx); return; }
}

void spu_func_00004788(spu_context* ctx) {
        ctx->gpr[87] = spu_a(ctx->gpr[100], ctx->gpr[26]);
        ctx->gpr[24] = spu_ls_read128(ctx, ctx->gpr[100]._u32[0] + ctx->gpr[26]._u32[0]);
        ctx->gpr[23] = spu_ai(ctx->gpr[87], 4);
        ctx->gpr[22] = spu_ls_read128(ctx, ctx->gpr[87]._u32[0] + ctx->gpr[25]._u32[0]);
        ctx->gpr[86] = spu_rotqby(ctx->gpr[24], ctx->gpr[87]);
        ctx->gpr[84] = spu_rotqby(ctx->gpr[22], ctx->gpr[23]);
        /* nop */;
        if (ctx->gpr[86]._u32[0] == 0) { ctx->pc = 0x4C6C; spu_func_00004C6C(ctx); return; }
        ctx->gpr[95] = spu_il(1);
        ctx->gpr[33] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x0);
        ctx->gpr[82] = spu_il(0);
        ctx->gpr[83] = spu_fsmbi(0x0);
        ctx->gpr[50] = spu_rotqbyi(ctx->gpr[33], 4);
        goto loc_000047D0;
        ctx->gpr[82] = spu_ai(ctx->gpr[82], 1);
        ctx->gpr[83] = spu_ai(ctx->gpr[83], 4);
        ctx->gpr[33] = spu_ceq(ctx->gpr[86], ctx->gpr[82]);
        if (ctx->gpr[33]._u32[0] != 0) { ctx->pc = 0x4CD4; spu_func_00004CD4(ctx); return; }
loc_000047D0:
        ctx->gpr[34] = spu_ceqi(ctx->gpr[50], -1);
        if (ctx->gpr[34]._u32[0] != 0) { ctx->pc = 0x4CE8; spu_func_00004CE8(ctx); return; }
        /* branch hint (ignored) */;
        ctx->gpr[42] = spu_a(ctx->gpr[82], ctx->gpr[82]);
        { ctx->pc = 0x47E0; spu_func_000047E0(ctx); return; }
}

void spu_func_000047E0(spu_context* ctx) {
        ctx->gpr[22] = spu_ila(0xFFFF);
        /* nop */;
        ctx->gpr[41] = spu_a(ctx->gpr[42], ctx->gpr[84]);
        ctx->gpr[39] = spu_ls_read128(ctx, ctx->gpr[42]._u32[0] + ctx->gpr[84]._u32[0]);
        { ctx->pc = 0x47F0; spu_func_000047F0(ctx); return; }
}

void spu_func_000047F0(spu_context* ctx) {
        ctx->gpr[40] = spu_ai(ctx->gpr[41], 14);
        ctx->gpr[38] = spu_rotqby(ctx->gpr[39], ctx->gpr[40]);
        { ctx->pc = 0x47F8; spu_func_000047F8(ctx); return; }
}

void spu_func_000047F8(spu_context* ctx) {
        ctx->gpr[37] = spu_and(ctx->gpr[38], ctx->gpr[22]);
        ctx->gpr[36] = spu_ceq(ctx->gpr[50], ctx->gpr[37]);
        /* nop */;
        if (ctx->gpr[36]._u32[0] == 0) { ctx->pc = 0x47C0; spu_func_000047C0(ctx); return; }
        ctx->gpr[16] = spu_il(28);
        ctx->gpr[8] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x10);
        ctx->gpr[15] = spu_ai(ctx->gpr[85], 28);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x20);
        ctx->gpr[11] = spu_shli(ctx->gpr[50], 6);
        ctx->gpr[13] = spu_ls_read128(ctx, ctx->gpr[85]._u32[0] + ctx->gpr[16]._u32[0]);
        ctx->gpr[31] = spu_andbi(ctx->gpr[93], 31);
        ctx->gpr[25] = spu_fsmbi(0x0);
        ctx->gpr[21] = spu_ila(0x10203);
        ctx->gpr[24] = spu_fsmbi(0xF);
        ctx->gpr[74] = spu_andbi(ctx->gpr[90], 31);
        ctx->gpr[12] = spu_il(12);
        ctx->gpr[71] = spu_andbi(ctx->gpr[91], 31);
        ctx->gpr[9] = spu_rotqbyi(ctx->gpr[7], 12);
        ctx->gpr[2] = spu_ai(ctx->gpr[87], 12);
        ctx->gpr[10] = spu_rotqby(ctx->gpr[13], ctx->gpr[15]);
        ctx->gpr[70] = spu_andbi(ctx->gpr[92], 31);
        ctx->gpr[21] = spu_selb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[65]);
        ctx->gpr[23] = spu_ilhu(0x4000);
        ctx->gpr[53] = spu_rotqbyi(ctx->gpr[7], 4);
        ctx->gpr[43] = spu_ilhu(0x3F80);
        ctx->gpr[21] = spu_selb(ctx->gpr[9], ctx->gpr[9], ctx->gpr[78]);
        ctx->gpr[19] = spu_a(ctx->gpr[11], ctx->gpr[10]);
        ctx->gpr[4] = spu_ls_read128(ctx, ctx->gpr[11]._u32[0] + ctx->gpr[10]._u32[0]);
        ctx->gpr[5] = spu_ls_read128(ctx, ctx->gpr[87]._u32[0] + ctx->gpr[12]._u32[0]);
        ctx->gpr[57] = spu_ls_read128(ctx, ctx->gpr[19]._u32[0] + 0x10);
        ctx->gpr[21] = spu_selb(ctx->gpr[53], ctx->gpr[53], ctx->gpr[60]);
        ctx->gpr[79] = spu_rotqbyi(ctx->gpr[7], 8);
        ctx->gpr[20] = spu_ls_read128(ctx, ctx->gpr[19]._u32[0] + 0x20);
        ctx->gpr[47] = spu_fs(ctx->gpr[8], ctx->gpr[4]);
        /* nop */;
        ctx->gpr[3] = spu_rotqby(ctx->gpr[5], ctx->gpr[2]);
        ctx->gpr[68] = spu_xor(ctx->gpr[57], ctx->gpr[94]);
        ctx->gpr[31] = spu_selb(ctx->gpr[57], ctx->gpr[57], ctx->gpr[63]);
        ctx->gpr[75] = spu_rotqbyi(ctx->gpr[57], 12);
        ctx->gpr[69] = spu_fs(ctx->gpr[25], ctx->gpr[68]);
        ctx->gpr[66] = spu_fm(ctx->gpr[68], ctx->gpr[78]);
        ctx->gpr[21] = spu_selb(ctx->gpr[79], ctx->gpr[79], ctx->gpr[56]);
        ctx->gpr[73] = spu_fm(ctx->gpr[47], ctx->gpr[63]);
        ctx->gpr[31] = spu_selb(ctx->gpr[47], ctx->gpr[47], ctx->gpr[72]);
        ctx->gpr[77] = spu_a(ctx->gpr[83], ctx->gpr[3]);
        ctx->gpr[21] = spu_selb(ctx->gpr[75], ctx->gpr[75], ctx->gpr[48]);
        ctx->gpr[53] = spu_ori(ctx->gpr[20], 0);
        ctx->gpr[76] = spu_ls_read128(ctx, ctx->gpr[83]._u32[0] + ctx->gpr[3]._u32[0]);
        ctx->gpr[74] = spu_selb(ctx->gpr[68], ctx->gpr[69], ctx->gpr[67]);
        ctx->gpr[71] = spu_selb(ctx->gpr[68], ctx->gpr[69], ctx->gpr[62]);
        ctx->gpr[73] = spu_fnms(ctx->gpr[57], ctx->gpr[72], ctx->gpr[64]);
        ctx->gpr[70] = spu_selb(ctx->gpr[68], ctx->gpr[69], ctx->gpr[55]);
        ctx->gpr[66] = spu_fma(ctx->gpr[65], ctx->gpr[67], ctx->gpr[61]);
        ctx->gpr[45] = spu_rotqby(ctx->gpr[76], ctx->gpr[77]);
        ctx->gpr[31] = spu_selb(ctx->gpr[64], ctx->gpr[64], ctx->gpr[51]);
        ctx->gpr[61] = spu_fma(ctx->gpr[60], ctx->gpr[62], ctx->gpr[54]);
        ctx->gpr[59] = spu_fm(ctx->gpr[51], ctx->gpr[63]);
        ctx->gpr[31] = spu_selb(ctx->gpr[51], ctx->gpr[51], ctx->gpr[58]);
        ctx->gpr[54] = spu_fma(ctx->gpr[56], ctx->gpr[55], ctx->gpr[33]);
        ctx->gpr[59] = spu_fnms(ctx->gpr[57], ctx->gpr[58], ctx->gpr[52]);
        ctx->gpr[31] = spu_selb(ctx->gpr[52], ctx->gpr[52], ctx->gpr[49]);
        ctx->gpr[49] = spu_fma(ctx->gpr[48], ctx->gpr[51], ctx->gpr[46]);
        ctx->gpr[47] = spu_fma(ctx->gpr[46], ctx->gpr[23], ctx->gpr[44]);
        /* nop */;
        ctx->gpr[24] = spu_shufb(ctx->gpr[44], ctx->gpr[43], ctx->gpr[38]);
        if (ctx->gpr[20]._u32[0] == 0) { ctx->pc = 0x4C44; spu_func_00004C44(ctx); return; }
        ctx->gpr[36] = spu_ori(ctx->gpr[21], 0);
        ctx->gpr[18] = spu_ls_read128(ctx, ctx->gpr[19]._u32[0] + 0x30);
        ctx->gpr[21] = spu_ceqi(ctx->gpr[45], 0);
        ctx->gpr[19] = spu_rotqbyi(ctx->gpr[33], 12);
        ctx->gpr[46] = spu_ori(ctx->gpr[22], 0);
        ctx->gpr[31] = spu_selb(ctx->gpr[33], ctx->gpr[33], ctx->gpr[32]);
        ctx->gpr[17] = spu_nor(ctx->gpr[21], ctx->gpr[21]);
        ctx->gpr[47] = spu_rotqbyi(ctx->gpr[20], 8);
        ctx->gpr[41] = spu_ori(ctx->gpr[23], 0);
        ctx->gpr[48] = spu_rotqbyi(ctx->gpr[20], 12);
        ctx->gpr[40] = spu_ori(ctx->gpr[24], 0);
        ctx->gpr[36] = spu_selb(ctx->gpr[19], ctx->gpr[19], ctx->gpr[37]);
        ctx->gpr[49] = spu_ori(ctx->gpr[18], 0);
        ctx->gpr[52] = spu_rotqbyi(ctx->gpr[18], 4);
        ctx->gpr[35] = spu_ori(ctx->gpr[25], 0);
        ctx->gpr[44] = spu_fsmbi(0x0);
        ctx->gpr[51] = spu_sfi(ctx->gpr[17], 0);
        ctx->gpr[54] = spu_il(1);
        ctx->gpr[43] = spu_a(ctx->gpr[44], ctx->gpr[44]);
        /* branch hint (ignored) */;
        ctx->gpr[39] = spu_il(0);
        /* nop */;
        ctx->gpr[30] = spu_a(ctx->gpr[43], ctx->gpr[48]);
        ctx->gpr[28] = spu_ls_read128(ctx, ctx->gpr[43]._u32[0] + ctx->gpr[48]._u32[0]);
        ctx->gpr[6] = spu_a(ctx->gpr[43], ctx->gpr[49]);
        ctx->gpr[26] = spu_ls_read128(ctx, ctx->gpr[43]._u32[0] + ctx->gpr[49]._u32[0]);
        { ctx->pc = 0x4968; spu_func_00004968(ctx); return; }
}

void spu_func_00004968(spu_context* ctx) {
        ctx->gpr[29] = spu_ai(ctx->gpr[30], 14);
        ctx->gpr[27] = spu_ai(ctx->gpr[6], 14);
        ctx->gpr[25] = spu_rotqby(ctx->gpr[28], ctx->gpr[29]);
        ctx->gpr[24] = spu_rotqby(ctx->gpr[26], ctx->gpr[27]);
        ctx->gpr[23] = spu_and(ctx->gpr[46], ctx->gpr[25]);
        ctx->gpr[22] = spu_and(ctx->gpr[46], ctx->gpr[24]);
        ctx->gpr[20] = spu_shli(ctx->gpr[23], 4);
        ctx->gpr[36] = spu_selb(ctx->gpr[22], ctx->gpr[22], ctx->gpr[42]);
        ctx->gpr[34] = spu_a(ctx->gpr[20], ctx->gpr[52]);
        { ctx->pc = 0x4BB0; spu_func_00004BB0(ctx); return; }
        ctx->gpr[75] = spu_ls_read128(ctx, ctx->gpr[34]._u32[0] + 0x0);
        ctx->gpr[73] = spu_ls_read128(ctx, ctx->gpr[34]._u32[0] + 0x10);
        ctx->gpr[71] = spu_ls_read128(ctx, ctx->gpr[34]._u32[0] + 0x20);
        ctx->gpr[70] = spu_ls_read128(ctx, ctx->gpr[34]._u32[0] + 0x30);
        /* nop */;
        /* branch hint (ignored) */;
        ctx->gpr[77] = spu_fm(ctx->gpr[75], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[75], ctx->gpr[75], ctx->gpr[76]);
        { ctx->pc = 0x49B0; spu_func_000049B0(ctx); return; }
}

void spu_func_000049B0(spu_context* ctx) {
        ctx->gpr[74] = spu_fm(ctx->gpr[73], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[73], ctx->gpr[73], ctx->gpr[72]);
        ctx->gpr[6] = spu_fm(ctx->gpr[71], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[71], ctx->gpr[71], ctx->gpr[67]);
        ctx->gpr[69] = spu_fm(ctx->gpr[70], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[70], ctx->gpr[70], ctx->gpr[65]);
        ctx->gpr[60] = spu_fm(ctx->gpr[75], ctx->gpr[38]);
        ctx->gpr[12] = spu_rotqbyi(ctx->gpr[75], 12);
        ctx->gpr[58] = spu_fm(ctx->gpr[73], ctx->gpr[38]);
        ctx->gpr[10] = spu_rotqbyi(ctx->gpr[73], 12);
        ctx->gpr[77] = spu_fnms(ctx->gpr[33], ctx->gpr[76], ctx->gpr[68]);
        ctx->gpr[5] = spu_rotqbyi(ctx->gpr[71], 12);
        ctx->gpr[74] = spu_fnms(ctx->gpr[33], ctx->gpr[72], ctx->gpr[66]);
        ctx->gpr[3] = spu_rotqbyi(ctx->gpr[70], 12);
        ctx->gpr[6] = spu_fnms(ctx->gpr[33], ctx->gpr[67], ctx->gpr[64]);
        ctx->gpr[36] = spu_selb(ctx->gpr[12], ctx->gpr[12], ctx->gpr[67]);
        ctx->gpr[69] = spu_fnms(ctx->gpr[33], ctx->gpr[65], ctx->gpr[63]);
        ctx->gpr[36] = spu_selb(ctx->gpr[10], ctx->gpr[10], ctx->gpr[65]);
        ctx->gpr[14] = spu_fm(ctx->gpr[71], ctx->gpr[38]);
        ctx->gpr[62] = spu_rotqbyi(ctx->gpr[60], 4);
        ctx->gpr[15] = spu_fm(ctx->gpr[70], ctx->gpr[38]);
        ctx->gpr[61] = spu_rotqbyi(ctx->gpr[58], 4);
        ctx->gpr[31] = spu_selb(ctx->gpr[68], ctx->gpr[68], ctx->gpr[9]);
        ctx->gpr[31] = spu_selb(ctx->gpr[66], ctx->gpr[66], ctx->gpr[8]);
        ctx->gpr[16] = spu_fa(ctx->gpr[60], ctx->gpr[62]);
        ctx->gpr[31] = spu_selb(ctx->gpr[64], ctx->gpr[64], ctx->gpr[21]);
        ctx->gpr[17] = spu_fa(ctx->gpr[58], ctx->gpr[61]);
        ctx->gpr[31] = spu_selb(ctx->gpr[63], ctx->gpr[63], ctx->gpr[7]);
        ctx->gpr[24] = spu_fm(ctx->gpr[9], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[9], ctx->gpr[9], ctx->gpr[59]);
        ctx->gpr[25] = spu_fm(ctx->gpr[8], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[8], ctx->gpr[8], ctx->gpr[57]);
        ctx->gpr[26] = spu_fm(ctx->gpr[21], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[21], ctx->gpr[21], ctx->gpr[56]);
        ctx->gpr[27] = spu_fm(ctx->gpr[7], ctx->gpr[32]);
        ctx->gpr[31] = spu_selb(ctx->gpr[7], ctx->gpr[7], ctx->gpr[55]);
        ctx->gpr[29] = spu_rotqbyi(ctx->gpr[14], 4);
        ctx->gpr[30] = spu_rotqbyi(ctx->gpr[15], 4);
        ctx->gpr[24] = spu_fnms(ctx->gpr[33], ctx->gpr[59], ctx->gpr[23]);
        ctx->gpr[28] = spu_rotqbyi(ctx->gpr[60], 8);
        ctx->gpr[25] = spu_fnms(ctx->gpr[33], ctx->gpr[57], ctx->gpr[22]);
        ctx->gpr[18] = spu_rotqbyi(ctx->gpr[58], 8);
        ctx->gpr[26] = spu_fnms(ctx->gpr[33], ctx->gpr[56], ctx->gpr[20]);
        ctx->gpr[79] = spu_rotqbyi(ctx->gpr[14], 8);
        ctx->gpr[27] = spu_fnms(ctx->gpr[33], ctx->gpr[55], ctx->gpr[19]);
        ctx->gpr[77] = spu_rotqbyi(ctx->gpr[15], 8);
        ctx->gpr[78] = spu_fa(ctx->gpr[14], ctx->gpr[29]);
        ctx->gpr[36] = spu_selb(ctx->gpr[5], ctx->gpr[5], ctx->gpr[62]);
        ctx->gpr[76] = spu_fa(ctx->gpr[15], ctx->gpr[30]);
        ctx->gpr[36] = spu_selb(ctx->gpr[3], ctx->gpr[3], ctx->gpr[59]);
        ctx->gpr[68] = spu_fa(ctx->gpr[16], ctx->gpr[28]);
        ctx->gpr[31] = spu_selb(ctx->gpr[23], ctx->gpr[23], ctx->gpr[13]);
        ctx->gpr[66] = spu_fa(ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[31] = spu_selb(ctx->gpr[22], ctx->gpr[22], ctx->gpr[11]);
        ctx->gpr[31] = spu_selb(ctx->gpr[20], ctx->gpr[20], ctx->gpr[4]);
        ctx->gpr[31] = spu_selb(ctx->gpr[19], ctx->gpr[19], ctx->gpr[2]);
        ctx->gpr[63] = spu_fa(ctx->gpr[78], ctx->gpr[79]);
        ctx->gpr[60] = spu_fa(ctx->gpr[76], ctx->gpr[77]);
        ctx->gpr[13] = spu_fma(ctx->gpr[37], ctx->gpr[9], ctx->gpr[74]);
        ctx->gpr[11] = spu_fma(ctx->gpr[37], ctx->gpr[8], ctx->gpr[72]);
        ctx->gpr[4] = spu_fma(ctx->gpr[37], ctx->gpr[21], ctx->gpr[6]);
        ctx->gpr[2] = spu_fma(ctx->gpr[37], ctx->gpr[7], ctx->gpr[69]);
        ctx->gpr[64] = spu_fa(ctx->gpr[67], ctx->gpr[68]);
        ctx->gpr[61] = spu_fa(ctx->gpr[65], ctx->gpr[66]);
        ctx->gpr[58] = spu_fa(ctx->gpr[62], ctx->gpr[63]);
        ctx->gpr[57] = spu_fa(ctx->gpr[59], ctx->gpr[60]);
        ctx->gpr[75] = spu_fma(ctx->gpr[74], ctx->gpr[41], ctx->gpr[55]);
        ctx->gpr[73] = spu_fma(ctx->gpr[72], ctx->gpr[41], ctx->gpr[29]);
        ctx->gpr[71] = spu_fma(ctx->gpr[6], ctx->gpr[41], ctx->gpr[27]);
        ctx->gpr[36] = spu_selb(ctx->gpr[64], ctx->gpr[64], ctx->gpr[56]);
        ctx->gpr[70] = spu_fma(ctx->gpr[69], ctx->gpr[41], ctx->gpr[25]);
        ctx->gpr[36] = spu_selb(ctx->gpr[61], ctx->gpr[61], ctx->gpr[30]);
        ctx->gpr[36] = spu_selb(ctx->gpr[58], ctx->gpr[58], ctx->gpr[28]);
        ctx->gpr[36] = spu_selb(ctx->gpr[57], ctx->gpr[57], ctx->gpr[26]);
        ctx->gpr[40] = spu_shufb(ctx->gpr[55], ctx->gpr[56], ctx->gpr[21]);
        ctx->gpr[40] = spu_shufb(ctx->gpr[29], ctx->gpr[30], ctx->gpr[18]);
        ctx->gpr[40] = spu_shufb(ctx->gpr[27], ctx->gpr[28], ctx->gpr[16]);
        ctx->gpr[40] = spu_shufb(ctx->gpr[25], ctx->gpr[26], ctx->gpr[15]);
        ctx->gpr[24] = spu_fcgt(ctx->gpr[21], ctx->gpr[35]);
        ctx->gpr[23] = spu_fcgt(ctx->gpr[18], ctx->gpr[35]);
        ctx->gpr[22] = spu_fcgt(ctx->gpr[16], ctx->gpr[35]);
        ctx->gpr[20] = spu_fcgt(ctx->gpr[15], ctx->gpr[35]);
        ctx->gpr[24] = spu_shufb(ctx->gpr[80], ctx->gpr[81], ctx->gpr[19]);
        ctx->gpr[23] = spu_shufb(ctx->gpr[80], ctx->gpr[81], ctx->gpr[17]);
        ctx->gpr[22] = spu_shufb(ctx->gpr[80], ctx->gpr[81], ctx->gpr[14]);
        ctx->gpr[20] = spu_shufb(ctx->gpr[80], ctx->gpr[81], ctx->gpr[5]);
        ctx->gpr[2] = spu_fm(ctx->gpr[19], ctx->gpr[21]);
        ctx->gpr[3] = spu_fm(ctx->gpr[17], ctx->gpr[18]);
        ctx->gpr[4] = spu_fm(ctx->gpr[14], ctx->gpr[16]);
        ctx->gpr[78] = spu_fm(ctx->gpr[5], ctx->gpr[15]);
        ctx->gpr[13] = spu_rotqbyi(ctx->gpr[2], 4);
        ctx->gpr[7] = spu_rotqbyi(ctx->gpr[3], 4);
        ctx->gpr[8] = spu_rotqbyi(ctx->gpr[4], 4);
        ctx->gpr[9] = spu_rotqbyi(ctx->gpr[78], 4);
        ctx->gpr[11] = spu_fa(ctx->gpr[2], ctx->gpr[13]);
        ctx->gpr[12] = spu_rotqbyi(ctx->gpr[2], 8);
        ctx->gpr[79] = spu_fa(ctx->gpr[3], ctx->gpr[7]);
        ctx->gpr[10] = spu_rotqbyi(ctx->gpr[3], 8);
        ctx->gpr[76] = spu_fa(ctx->gpr[4], ctx->gpr[8]);
        ctx->gpr[77] = spu_rotqbyi(ctx->gpr[4], 8);
        ctx->gpr[74] = spu_fa(ctx->gpr[78], ctx->gpr[9]);
        ctx->gpr[75] = spu_rotqbyi(ctx->gpr[78], 8);
        ctx->gpr[73] = spu_rotqbyi(ctx->gpr[2], 12);
        ctx->gpr[71] = spu_rotqbyi(ctx->gpr[3], 12);
        ctx->gpr[72] = spu_fa(ctx->gpr[11], ctx->gpr[12]);
        ctx->gpr[69] = spu_rotqbyi(ctx->gpr[4], 12);
        ctx->gpr[70] = spu_fa(ctx->gpr[79], ctx->gpr[10]);
        ctx->gpr[67] = spu_rotqbyi(ctx->gpr[78], 12);
        ctx->gpr[68] = spu_fa(ctx->gpr[76], ctx->gpr[77]);
        ctx->gpr[66] = spu_fa(ctx->gpr[74], ctx->gpr[75]);
        ctx->gpr[65] = spu_fa(ctx->gpr[72], ctx->gpr[73]);
        ctx->gpr[64] = spu_fa(ctx->gpr[70], ctx->gpr[71]);
        ctx->gpr[63] = spu_fa(ctx->gpr[68], ctx->gpr[69]);
        ctx->gpr[62] = spu_fa(ctx->gpr[66], ctx->gpr[67]);
        ctx->gpr[6] = spu_fcgt(ctx->gpr[65], ctx->gpr[35]);
        ctx->gpr[7] = spu_fcgt(ctx->gpr[64], ctx->gpr[35]);
        ctx->gpr[8] = spu_fcgt(ctx->gpr[63], ctx->gpr[35]);
        ctx->gpr[9] = spu_fcgt(ctx->gpr[62], ctx->gpr[35]);
        ctx->gpr[60] = spu_or(ctx->gpr[6], ctx->gpr[7]);
        ctx->gpr[61] = spu_or(ctx->gpr[8], ctx->gpr[9]);
        ctx->gpr[59] = spu_or(ctx->gpr[60], ctx->gpr[61]);
        ctx->gpr[58] = spu_clgti(ctx->gpr[59], 0);
        ctx->gpr[57] = spu_rotmi(ctx->gpr[58], 97);
        ctx->gpr[56] = spu_orx(ctx->gpr[57]);
        ctx->gpr[55] = spu_ceqi(ctx->gpr[56], 1);
        if (ctx->gpr[55]._u32[0] != 0) { ctx->pc = 0x4C98; spu_func_00004C98(ctx); return; }
        ctx->gpr[39] = spu_ai(ctx->gpr[39], 4);
        ctx->gpr[34] = spu_ai(ctx->gpr[34], 64);
        ctx->gpr[6] = spu_clgt(ctx->gpr[42], ctx->gpr[39]);
        ctx->gpr[71] = spu_rotmi(ctx->gpr[6], 97);
        ctx->gpr[70] = spu_orx(ctx->gpr[71]);
        if (ctx->gpr[70]._u32[0] != 0) { ctx->pc = 0x4990; spu_func_00004990(ctx); return; }
        ctx->gpr[15] = spu_a(ctx->gpr[43], ctx->gpr[47]);
        ctx->gpr[23] = spu_ls_read128(ctx, ctx->gpr[43]._u32[0] + ctx->gpr[47]._u32[0]);
        /* nop */;
        /* TODO spu: gbb $r28, $r6, $r0 */;
        { ctx->pc = 0x4BD0; spu_func_00004BD0(ctx); return; }
}

void spu_func_00004BD0(spu_context* ctx) {
        ctx->gpr[16] = spu_ai(ctx->gpr[15], 14);
        /* branch hint (ignored) */;
        ctx->gpr[18] = spu_ceqhi(ctx->gpr[28], 0);
        ctx->gpr[17] = spu_rotqby(ctx->gpr[23], ctx->gpr[16]);
        { ctx->pc = 0x4BE0; spu_func_00004BE0(ctx); return; }
}

void spu_func_00004BE0(spu_context* ctx) {
        ctx->gpr[22] = spu_xshw(ctx->gpr[18]);
        ctx->gpr[19] = spu_sfi(ctx->gpr[22], 0);
        ctx->gpr[20] = spu_rothmi(ctx->gpr[17], 123);
        ctx->gpr[11] = spu_andi(ctx->gpr[17], 31);
        ctx->gpr[9] = spu_and(ctx->gpr[19], ctx->gpr[51]);
        ctx->gpr[73] = spu_shl(ctx->gpr[54], ctx->gpr[11]);
        ctx->gpr[13] = spu_and(ctx->gpr[46], ctx->gpr[20]);
        ctx->gpr[8] = spu_ceqbi(ctx->gpr[9], 0);
        ctx->gpr[4] = spu_shli(ctx->gpr[13], 2);
        ctx->gpr[21] = spu_xsbh(ctx->gpr[8]);
        ctx->gpr[2] = spu_ceqhi(ctx->gpr[21], 0);
        /* nop */;
        ctx->gpr[79] = spu_a(ctx->gpr[4], ctx->gpr[45]);
        ctx->gpr[78] = spu_ls_read128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[45]._u32[0]);
        ctx->gpr[7] = spu_nor(ctx->gpr[2], ctx->gpr[2]);
        ctx->gpr[39] = spu_xshw(ctx->gpr[7]);
        ctx->gpr[75] = spu_rotqby(ctx->gpr[78], ctx->gpr[79]);
        ctx->gpr[43] = spu_and(ctx->gpr[73], ctx->gpr[75]);
        ctx->gpr[42] = spu_ceqi(ctx->gpr[43], 0);
        ctx->gpr[34] = spu_nor(ctx->gpr[42], ctx->gpr[42]);
        ctx->gpr[2] = spu_or(ctx->gpr[39], ctx->gpr[34]);
        if (ctx->gpr[2]._u16[1] == 0) goto loc_00004C48;
        ctx->gpr[44] = spu_ai(ctx->gpr[44], 1);
        ctx->gpr[59] = spu_clgt(ctx->gpr[53], ctx->gpr[44]);
        if (ctx->gpr[59]._u32[0] != 0) { ctx->pc = 0x4948; spu_func_00004948(ctx); return; }
        ctx->gpr[2] = spu_il(1);
loc_00004C48:
        ctx->gpr[32] = spu_ceqbi(ctx->gpr[2], 0);
        ctx->gpr[31] = spu_xsbh(ctx->gpr[32]);
        /* nop */;
        if (ctx->gpr[31]._u16[1] == 0) { ctx->pc = 0x47C0; spu_func_000047C0(ctx); return; }
        ctx->gpr[32] = spu_il(8);
        ctx->gpr[95] = spu_fsmbi(0x0);
        ctx->gpr[31] = spu_ai(ctx->gpr[85], 8);
        { ctx->pc = 0x4C64; spu_func_00004C64(ctx); return; }
}

void spu_func_00004C64(spu_context* ctx) {
        ctx->gpr[30] = spu_ls_read128(ctx, ctx->gpr[85]._u32[0] + ctx->gpr[32]._u32[0]);
        { ctx->pc = 0x4C68; spu_func_00004C68(ctx); return; }
}

void spu_func_00004C68(spu_context* ctx) {
        ctx->gpr[6] = spu_rotqby(ctx->gpr[30], ctx->gpr[31]);
        /* branch hint (ignored) */;
        ctx->gpr[35] = spu_ceqbi(ctx->gpr[97], 0);
        ctx->gpr[96] = spu_ai(ctx->gpr[96], 1);
        ctx->gpr[50] = spu_xsbh(ctx->gpr[35]);
        ctx->gpr[84] = spu_clgt(ctx->gpr[6], ctx->gpr[96]);
        ctx->gpr[86] = spu_ceqhi(ctx->gpr[50], 0);
        /* nop */;
        ctx->gpr[100] = spu_ai(ctx->gpr[100], 16);
        { ctx->pc = 0x4C8C; spu_func_00004C8C(ctx); return; }
}

void spu_func_00004C8C(spu_context* ctx) {
        ctx->gpr[86] = spu_shufb(ctx->gpr[95], ctx->gpr[97], ctx->gpr[97]);
        if (ctx->gpr[84]._u32[0] != 0) { ctx->pc = 0x4768; spu_func_00004768(ctx); return; }
        { ctx->pc = 0x4670; spu_func_00004670(ctx); return; }
        ctx->gpr[58] = spu_sf(ctx->gpr[39], ctx->gpr[42]);
        /* branch hint (ignored) */;
        ctx->gpr[26] = spu_clgti(ctx->gpr[58], 3);
        ctx->gpr[25] = spu_clgti(ctx->gpr[58], 1);
        ctx->gpr[57] = spu_clgti(ctx->gpr[58], 2);
        ctx->gpr[56] = spu_orc(ctx->gpr[7], ctx->gpr[25]);
        ctx->gpr[55] = spu_orc(ctx->gpr[8], ctx->gpr[57]);
        ctx->gpr[27] = spu_orc(ctx->gpr[9], ctx->gpr[26]);
        { ctx->pc = 0x4CB8; spu_func_00004CB8(ctx); return; }
}

void spu_func_00004CB8(spu_context* ctx) {
        ctx->gpr[29] = spu_a(ctx->gpr[6], ctx->gpr[56]);
        ctx->gpr[5] = spu_a(ctx->gpr[55], ctx->gpr[27]);
        ctx->gpr[14] = spu_a(ctx->gpr[29], ctx->gpr[5]);
        ctx->gpr[3] = spu_ai(ctx->gpr[14], 4);
        ctx->gpr[30] = spu_a(ctx->gpr[39], ctx->gpr[3]);
        ctx->gpr[6] = spu_clgt(ctx->gpr[42], ctx->gpr[30]);
        { ctx->pc = 0x4BC0; spu_func_00004BC0(ctx); return; }
        ctx->gpr[87] = spu_il(8);
        ctx->gpr[83] = spu_ai(ctx->gpr[85], 8);
        ctx->gpr[82] = spu_ls_read128(ctx, ctx->gpr[85]._u32[0] + ctx->gpr[87]._u32[0]);
        ctx->gpr[6] = spu_rotqby(ctx->gpr[82], ctx->gpr[83]);
        { ctx->pc = 0x4C6C; spu_func_00004C6C(ctx); return; }
        ctx->gpr[3] = spu_ila(0x4FF0);
        ctx->gpr[4] = spu_ila(0x5010);
        ctx->gpr[5] = spu_ila(0x5030);
        { ctx->pc = 0x4CF4; spu_func_00004CF4(ctx); return; }
}

void spu_func_00004CF4(spu_context* ctx) {
        /* nop */;
        ctx->gpr[6] = spu_il(94);
        ctx->gpr[0] = spu_splat_u32(0x4D00); spu_func_00004DC0(ctx);
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        ctx->gpr[35] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x0);
        { ctx->pc = 0x4D08; spu_func_00004D08(ctx); return; }
}

void spu_func_00004D08(spu_context* ctx) {
        ctx->gpr[50] = spu_rotqbyi(ctx->gpr[35], 4);
        { ctx->pc = 0x47D8; spu_func_000047D8(ctx); return; }
        ctx->gpr[81] = spu_il(0);
        ctx->gpr[82] = spu_fsmbi(0x0);
        ctx->gpr[83] = spu_il(1023);
        /* nop */;
        ctx->gpr[3] = spu_ila(0x4FF0);
}

void spu_func_00004D20(spu_context* ctx) {
        ctx->gpr[3] = spu_ila(0x4FF0);
}

void spu_func_00004D30(spu_context* ctx) {
        ctx->gpr[5] = spu_ila(0x5090);
        ctx->gpr[6] = spu_il(107);
        ctx->gpr[38] = spu_a(ctx->gpr[82], ctx->gpr[40]);
        ctx->gpr[37] = spu_ls_read128(ctx, ctx->gpr[82]._u32[0] + ctx->gpr[40]._u32[0]);
        { ctx->pc = 0x4D40; spu_func_00004D40(ctx); return; }
}

void spu_func_00004D40(spu_context* ctx) {
        ctx->gpr[80] = spu_rotqby(ctx->gpr[37], ctx->gpr[38]);
        ctx->gpr[36] = spu_clgt(ctx->gpr[80], ctx->gpr[83]);
        if (ctx->gpr[36]._u32[0] == 0) goto loc_00004D60;
        ctx->gpr[0] = spu_splat_u32(0x4D50); spu_func_00004DC0(ctx);
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        ctx->gpr[41] = spu_ls_read128(ctx, ctx->gpr[88]._u32[0] + 0x0);
        /* nop */;
        ctx->gpr[9] = spu_rotqbyi(ctx->gpr[41], 8);
loc_00004D60:
        ctx->gpr[66] = spu_rotmi(ctx->gpr[80], 122);
        ctx->gpr[64] = spu_fsmbi(0x101);
        ctx->gpr[63] = spu_andi(ctx->gpr[80], 63);
        /* branch hint (ignored) */;
        ctx->gpr[81] = spu_ai(ctx->gpr[81], 1);
}

void spu_func_00004D70(spu_context* ctx) {
        ctx->gpr[81] = spu_ai(ctx->gpr[81], 1);
}

void spu_func_00004D80(spu_context* ctx) {
        ctx->gpr[44] = spu_clgt(ctx->gpr[9], ctx->gpr[81]);
        /* nop */;
        ctx->gpr[82] = spu_ai(ctx->gpr[82], 4);
        ctx->gpr[61] = spu_rotqbyi(ctx->gpr[62], 8);
        ctx->gpr[49] = spu_a(ctx->gpr[46], ctx->gpr[99]);
        ctx->gpr[47] = spu_ls_read128(ctx, ctx->gpr[46]._u32[0] + ctx->gpr[99]._u32[0]);
        ctx->gpr[53] = spu_cdx(ctx->gpr[46], ctx->gpr[99]);
        ctx->gpr[24] = spu_shlqbybi(ctx->gpr[61], ctx->gpr[60]);
        ctx->gpr[52] = spu_rotqby(ctx->gpr[47], ctx->gpr[49]);
        ctx->gpr[48] = spu_shlqbi(ctx->gpr[24], ctx->gpr[60]);
        ctx->gpr[45] = spu_or(ctx->gpr[52], ctx->gpr[48]);
        ctx->gpr[53] = spu_selb(ctx->gpr[45], ctx->gpr[47], ctx->gpr[51]);
        spu_ls_write128(ctx, ctx->gpr[46]._u32[0] + ctx->gpr[99]._u32[0], ctx->gpr[51]);
        if (ctx->gpr[44]._u32[0] != 0) { ctx->pc = 0x4D20; spu_func_00004D20(ctx); return; }
        { ctx->pc = 0x46B0; spu_func_000046B0(ctx); return; }
        /* nop */;
        ctx->gpr[78] = spu_rdch(ctx, SPU_RdMachStat);
        ctx->gpr[78] = spu_andi(ctx->gpr[78], 1);
        ctx->gpr[2] = spu_splat_u32(0x4DCC); spu_func_00004DCC(ctx);
loc_00004DCC:
        ctx->gpr[2] = spu_ai(ctx->gpr[2], 8);
        ctx->pc = ctx->gpr[2]._u32[0]; spu_indirect_branch(ctx); return;
        ctx->gpr[2] = spu_splat_u32(spu_rchcnt(ctx, SPU_RdInMbox));
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x100, ctx->gpr[3]);
}

void spu_func_00004DE0(spu_context* ctx) {
        if (ctx->gpr[2]._u32[0] != 0) { ctx->pc = 0x4E44; spu_func_00004E44(ctx); return; }
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xF0, ctx->gpr[4]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xE0, ctx->gpr[5]);
        { ctx->pc = 0x4DEC; spu_func_00004DEC(ctx); return; }
}

void spu_func_00004DEC(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xD0, ctx->gpr[6]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xC0, ctx->gpr[7]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xB0, ctx->gpr[8]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0xA0, ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x90, ctx->gpr[10]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x80, ctx->gpr[11]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x70, ctx->gpr[12]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[13]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x50, ctx->gpr[14]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[15]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[16]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[17]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[18]);
        ctx->gpr[2] = spu_or(ctx->gpr[2], ctx->gpr[1]);
        ctx->gpr[2] = spu_ai(ctx->gpr[2], -256);
        spu_wrch(ctx, SPU_WrOutMbox, ctx->gpr[2]);
        /* sync */;
        ctx->gpr[3] = spu_ilhu(0x100);
        spu_wrch(ctx, SPU_WrOutIntrMbox, ctx->gpr[3]);
        ctx->gpr[3] = spu_rdch(ctx, SPU_RdInMbox);
        if (ctx->gpr[3]._u32[0] != 0) goto loc_00004E44;
        ctx->gpr[3] = spu_rdch(ctx, SPU_RdInMbox);
loc_00004E44:
        if (ctx->gpr[78]._u32[0] == 0) { ctx->pc = ctx->gpr[0]._u32[0]; spu_indirect_branch(ctx); return; }
        return;
        /* nop */;
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x10, ctx->gpr[80]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x20, ctx->gpr[81]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x30, ctx->gpr[82]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x40, ctx->gpr[126]);
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + 0x10, ctx->gpr[0]);
        { ctx->pc = 0x4E64; spu_func_00004E64(ctx); return; }
}

void spu_func_00004E64(spu_context* ctx) {
        spu_ls_write128(ctx, ctx->gpr[1]._u32[0] + -0x60, ctx->gpr[1]);
        ctx->gpr[1] = spu_ai(ctx->gpr[1], -96);
}

void spu_func_00004EA8(spu_context* ctx) {
        ctx->gpr[3] = spu_rotqby(ctx->gpr[7], ctx->gpr[80]);
        ctx->gpr[2] = spu_ceqi(ctx->gpr[3], -1);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = 0x4F58; spu_func_00004F58(ctx); return; }
        /* branch hint (ignored) */;
        ctx->gpr[2] = spu_ls_read128(ctx, 0x5110);
        { ctx->pc = 0x4EBC; spu_func_00004EBC(ctx); return; }
}

void spu_func_00004EBC(spu_context* ctx) {
        ctx->gpr[2] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x20);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x0);
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[2]._u32[0] + 0x10);
        ctx->gpr[4] = spu_rotqbyi(ctx->gpr[3], 4);
        ctx->gpr[5] = spu_rotqbyi(ctx->gpr[3], 8);
        ctx->gpr[6] = spu_rotqbyi(ctx->gpr[3], 12);
        { ctx->pc = 0x4ED4; spu_func_00004ED4(ctx); return; }
}

void spu_func_00004ED4(spu_context* ctx) {
        ctx->gpr[8] = spu_rotqbyi(ctx->gpr[7], 4);
        ctx->gpr[9] = spu_rotqbyi(ctx->gpr[7], 8);
        ctx->gpr[10] = spu_rotqbyi(ctx->gpr[7], 12);
        ctx->gpr[79] = spu_rdch(ctx, SPU_RdDec);
        ctx->gpr[82] = spu_sf(ctx->gpr[79], ctx->gpr[82]);
        ctx->gpr[0] = spu_ila(0x4F4C);
        ctx->gpr[0] = spu_a(ctx->gpr[0], ctx->gpr[126]);
        if (ctx->gpr[81]._u32[0] == 0) { ctx->pc = 0x3FE0; spu_func_00003FE0(ctx); return; }
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        { ctx->pc = 0x3FE0; spu_func_00003FE0(ctx); return; }
        ctx->gpr[81] = spu_rdch(ctx, SPU_RdDec);
        ctx->gpr[80] = spu_ila(0x515C);
        ctx->gpr[80] = spu_a(ctx->gpr[80], ctx->gpr[126]);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotqby(ctx->gpr[3], ctx->gpr[80]);
        if (ctx->gpr[3]._u32[0] != 0) { ctx->pc = 0x4F78; spu_func_00004F78(ctx); return; }
        ctx->gpr[79] = spu_rdch(ctx, SPU_RdDec);
}

void spu_func_00004F34(spu_context* ctx) {
        ctx->gpr[0] = spu_ls_read128(ctx, ctx->gpr[1]._u32[0] + 0x10);
        return;
        /* branch hint (ignored) */;
        ctx->gpr[5] = spu_il(0);
loc_00004F44:
        spu_ls_write128(ctx, ctx->gpr[3]._u32[0] + ctx->gpr[126]._u32[0], ctx->gpr[5]);
        ctx->gpr[3] = spu_ai(ctx->gpr[3], 16);
        ctx->gpr[6] = spu_clgt(ctx->gpr[4], ctx->gpr[3]);
        if (ctx->gpr[6]._u32[0] != 0) goto loc_00004F44;
        { ctx->pc = 0x4E9C; spu_func_00004E9C(ctx); return; }
        ctx->gpr[80] = spu_ai(ctx->gpr[80], -4);
        { ctx->pc = 0x4F5C; spu_func_00004F5C(ctx); return; }
}

void spu_func_00004F4C(spu_context* ctx) {
        ctx->gpr[6] = spu_clgt(ctx->gpr[4], ctx->gpr[3]);
}

void spu_func_00004F5C(spu_context* ctx) {
        ctx->gpr[3] = spu_a(ctx->gpr[3], ctx->gpr[126]);
        ctx->gpr[0] = spu_splat_u32(0x4F64); ctx->pc = ctx->gpr[3]._u32[0]; spu_indirect_branch(ctx);
        { ctx->pc = 0x4F64; spu_func_00004F64(ctx); return; }
}

void spu_func_00004F64(spu_context* ctx) {
        ctx->gpr[7] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotqby(ctx->gpr[7], ctx->gpr[80]);
        ctx->gpr[2] = spu_ceqi(ctx->gpr[3], -1);
        if (ctx->gpr[2]._u32[0] == 0) { ctx->pc = 0x4F58; spu_func_00004F58(ctx); return; }
        { ctx->pc = 0x4EB4; spu_func_00004EB4(ctx); return; }
}

void spu_func_00004F78(spu_context* ctx) {
loc_00004F78:
        ctx->gpr[3] = spu_a(ctx->gpr[3], ctx->gpr[126]);
        ctx->gpr[0] = spu_splat_u32(0x4F80); ctx->pc = ctx->gpr[3]._u32[0]; spu_indirect_branch(ctx);
        ctx->gpr[80] = spu_ai(ctx->gpr[80], 4);
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + 0x0);
        ctx->gpr[3] = spu_rotqby(ctx->gpr[3], ctx->gpr[80]);
        if (ctx->gpr[3]._u32[0] != 0) goto loc_00004F78;
        { ctx->pc = 0x4F14; spu_func_00004F14(ctx); return; }
        /* nop */;
        { ctx->pc = 0x4F98; spu_func_00004F98(ctx); return; }
}

void spu_func_00004F84(spu_context* ctx) {
        ctx->gpr[3] = spu_ls_read128(ctx, ctx->gpr[80]._u32[0] + 0x0);
}

void spu_func_00004F98(spu_context* ctx) {
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
        /* TODO spu: .word 0x0A415353 */;
        /* TODO spu: .word 0x4552543A */;
        if (ctx->gpr[37]._u16[1] != 0) { ctx->pc = ctx->gpr[20]._u32[0]; spu_indirect_branch(ctx); return; }
        /* TODO spu: .word 0x733A2575 */;
        /* TODO spu: .word 0x0A000000 */;
}

void spu_func_00004FA0(spu_context* ctx) {
        /* TODO spu: .word 0x0A415353 */;
}

void spu_func_00004FF0(spu_context* ctx) {
        ctx->gpr[47] = spu_mpyui(ctx->gpr[88], 433);
}

void spu_func_00005010(spu_context* ctx) {
        /* TODO spu: .word 0x696E6465 */;
}

void spu_func_00005030(spu_context* ctx) {
        /* TODO spu: .word 0x28290000 */;
}

void spu_func_00005060(spu_context* ctx) {
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

void spu_func_00005090(spu_context* ctx) {
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

void spu_func_00005150(spu_context* ctx) {
        ctx->gpr[94] = spu_mpya(ctx->gpr[1], ctx->gpr[123], ctx->gpr[6]);
}

void spu_func_00005180(spu_context* ctx) {
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

/* Indirect-dispatch stubs for cross-function targets the
 * function detector did not seed (typically conditional
 * branches that escape a function's range). */
void spu_func_00003FE0(spu_context* ctx) {
    ctx->pc = 0x3FE0u; spu_indirect_branch(ctx);
}
void spu_func_000041E0(spu_context* ctx) {
    ctx->pc = 0x41E0u; spu_indirect_branch(ctx);
}
void spu_func_00004290(spu_context* ctx) {
    ctx->pc = 0x4290u; spu_indirect_branch(ctx);
}
void spu_func_000042E0(spu_context* ctx) {
    ctx->pc = 0x42E0u; spu_indirect_branch(ctx);
}
void spu_func_000042F0(spu_context* ctx) {
    ctx->pc = 0x42F0u; spu_indirect_branch(ctx);
}
void spu_func_00004338(spu_context* ctx) {
    ctx->pc = 0x4338u; spu_indirect_branch(ctx);
}
void spu_func_000043B4(spu_context* ctx) {
    ctx->pc = 0x43B4u; spu_indirect_branch(ctx);
}
void spu_func_000043E8(spu_context* ctx) {
    ctx->pc = 0x43E8u; spu_indirect_branch(ctx);
}
void spu_func_00004418(spu_context* ctx) {
    ctx->pc = 0x4418u; spu_indirect_branch(ctx);
}
void spu_func_00004464(spu_context* ctx) {
    ctx->pc = 0x4464u; spu_indirect_branch(ctx);
}
void spu_func_00004470(spu_context* ctx) {
    ctx->pc = 0x4470u; spu_indirect_branch(ctx);
}
void spu_func_000044C0(spu_context* ctx) {
    ctx->pc = 0x44C0u; spu_indirect_branch(ctx);
}
void spu_func_000044D0(spu_context* ctx) {
    ctx->pc = 0x44D0u; spu_indirect_branch(ctx);
}
void spu_func_00004534(spu_context* ctx) {
    ctx->pc = 0x4534u; spu_indirect_branch(ctx);
}
void spu_func_0000453C(spu_context* ctx) {
    ctx->pc = 0x453Cu; spu_indirect_branch(ctx);
}
void spu_func_00004544(spu_context* ctx) {
    ctx->pc = 0x4544u; spu_indirect_branch(ctx);
}
void spu_func_0000454C(spu_context* ctx) {
    ctx->pc = 0x454Cu; spu_indirect_branch(ctx);
}
void spu_func_00004568(spu_context* ctx) {
    ctx->pc = 0x4568u; spu_indirect_branch(ctx);
}
void spu_func_00004598(spu_context* ctx) {
    ctx->pc = 0x4598u; spu_indirect_branch(ctx);
}
void spu_func_00004638(spu_context* ctx) {
    ctx->pc = 0x4638u; spu_indirect_branch(ctx);
}
void spu_func_00004670(spu_context* ctx) {
    ctx->pc = 0x4670u; spu_indirect_branch(ctx);
}
void spu_func_000046B0(spu_context* ctx) {
    ctx->pc = 0x46B0u; spu_indirect_branch(ctx);
}
void spu_func_000046C8(spu_context* ctx) {
    ctx->pc = 0x46C8u; spu_indirect_branch(ctx);
}
void spu_func_00004730(spu_context* ctx) {
    ctx->pc = 0x4730u; spu_indirect_branch(ctx);
}
void spu_func_00004768(spu_context* ctx) {
    ctx->pc = 0x4768u; spu_indirect_branch(ctx);
}
void spu_func_000047C0(spu_context* ctx) {
    ctx->pc = 0x47C0u; spu_indirect_branch(ctx);
}
void spu_func_000047D8(spu_context* ctx) {
    ctx->pc = 0x47D8u; spu_indirect_branch(ctx);
}
void spu_func_00004948(spu_context* ctx) {
    ctx->pc = 0x4948u; spu_indirect_branch(ctx);
}
void spu_func_00004990(spu_context* ctx) {
    ctx->pc = 0x4990u; spu_indirect_branch(ctx);
}
void spu_func_00004BB0(spu_context* ctx) {
    ctx->pc = 0x4BB0u; spu_indirect_branch(ctx);
}
void spu_func_00004BC0(spu_context* ctx) {
    ctx->pc = 0x4BC0u; spu_indirect_branch(ctx);
}
void spu_func_00004C44(spu_context* ctx) {
    ctx->pc = 0x4C44u; spu_indirect_branch(ctx);
}
void spu_func_00004C6C(spu_context* ctx) {
    ctx->pc = 0x4C6Cu; spu_indirect_branch(ctx);
}
void spu_func_00004C98(spu_context* ctx) {
    ctx->pc = 0x4C98u; spu_indirect_branch(ctx);
}
void spu_func_00004CD4(spu_context* ctx) {
    ctx->pc = 0x4CD4u; spu_indirect_branch(ctx);
}
void spu_func_00004CE8(spu_context* ctx) {
    ctx->pc = 0x4CE8u; spu_indirect_branch(ctx);
}
void spu_func_00004D10(spu_context* ctx) {
    ctx->pc = 0x4D10u; spu_indirect_branch(ctx);
}
void spu_func_00004DC0(spu_context* ctx) {
    ctx->pc = 0x4DC0u; spu_indirect_branch(ctx);
}
void spu_func_00004DCC(spu_context* ctx) {
    ctx->pc = 0x4DCCu; spu_indirect_branch(ctx);
}
void spu_func_00004E44(spu_context* ctx) {
    ctx->pc = 0x4E44u; spu_indirect_branch(ctx);
}
void spu_func_00004E9C(spu_context* ctx) {
    ctx->pc = 0x4E9Cu; spu_indirect_branch(ctx);
}
void spu_func_00004EB4(spu_context* ctx) {
    ctx->pc = 0x4EB4u; spu_indirect_branch(ctx);
}
void spu_func_00004F14(spu_context* ctx) {
    ctx->pc = 0x4F14u; spu_indirect_branch(ctx);
}
void spu_func_00004F58(spu_context* ctx) {
    ctx->pc = 0x4F58u; spu_indirect_branch(ctx);
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x00004000u, spu_func_00004000, "spu_func_00004000" },
    { 0x00004040u, spu_func_00004040, "spu_func_00004040" },
    { 0x00004058u, spu_func_00004058, "spu_func_00004058" },
    { 0x00004078u, spu_func_00004078, "spu_func_00004078" },
    { 0x00004080u, spu_func_00004080, "spu_func_00004080" },
    { 0x000040B0u, spu_func_000040B0, "spu_func_000040B0" },
    { 0x000040C0u, spu_func_000040C0, "spu_func_000040C0" },
    { 0x000040C8u, spu_func_000040C8, "spu_func_000040C8" },
    { 0x000040F0u, spu_func_000040F0, "spu_func_000040F0" },
    { 0x000040F8u, spu_func_000040F8, "spu_func_000040F8" },
    { 0x00004128u, spu_func_00004128, "spu_func_00004128" },
    { 0x00004200u, spu_func_00004200, "spu_func_00004200" },
    { 0x000042B0u, spu_func_000042B0, "spu_func_000042B0" },
    { 0x00004300u, spu_func_00004300, "spu_func_00004300" },
    { 0x00004310u, spu_func_00004310, "spu_func_00004310" },
    { 0x00004358u, spu_func_00004358, "spu_func_00004358" },
    { 0x00004360u, spu_func_00004360, "spu_func_00004360" },
    { 0x000043D4u, spu_func_000043D4, "spu_func_000043D4" },
    { 0x00004408u, spu_func_00004408, "spu_func_00004408" },
    { 0x00004438u, spu_func_00004438, "spu_func_00004438" },
    { 0x00004448u, spu_func_00004448, "spu_func_00004448" },
    { 0x00004484u, spu_func_00004484, "spu_func_00004484" },
    { 0x00004490u, spu_func_00004490, "spu_func_00004490" },
    { 0x000044C8u, spu_func_000044C8, "spu_func_000044C8" },
    { 0x000044E0u, spu_func_000044E0, "spu_func_000044E0" },
    { 0x000044F0u, spu_func_000044F0, "spu_func_000044F0" },
    { 0x000044F8u, spu_func_000044F8, "spu_func_000044F8" },
    { 0x00004518u, spu_func_00004518, "spu_func_00004518" },
    { 0x00004528u, spu_func_00004528, "spu_func_00004528" },
    { 0x00004538u, spu_func_00004538, "spu_func_00004538" },
    { 0x00004540u, spu_func_00004540, "spu_func_00004540" },
    { 0x00004550u, spu_func_00004550, "spu_func_00004550" },
    { 0x00004554u, spu_func_00004554, "spu_func_00004554" },
    { 0x0000455Cu, spu_func_0000455C, "spu_func_0000455C" },
    { 0x00004564u, spu_func_00004564, "spu_func_00004564" },
    { 0x0000456Cu, spu_func_0000456C, "spu_func_0000456C" },
    { 0x00004570u, spu_func_00004570, "spu_func_00004570" },
    { 0x00004588u, spu_func_00004588, "spu_func_00004588" },
    { 0x000045B8u, spu_func_000045B8, "spu_func_000045B8" },
    { 0x000045C0u, spu_func_000045C0, "spu_func_000045C0" },
    { 0x000045D8u, spu_func_000045D8, "spu_func_000045D8" },
    { 0x00004658u, spu_func_00004658, "spu_func_00004658" },
    { 0x00004690u, spu_func_00004690, "spu_func_00004690" },
    { 0x000046C4u, spu_func_000046C4, "spu_func_000046C4" },
    { 0x000046D0u, spu_func_000046D0, "spu_func_000046D0" },
    { 0x000046E8u, spu_func_000046E8, "spu_func_000046E8" },
    { 0x00004750u, spu_func_00004750, "spu_func_00004750" },
    { 0x00004788u, spu_func_00004788, "spu_func_00004788" },
    { 0x000047E0u, spu_func_000047E0, "spu_func_000047E0" },
    { 0x000047F0u, spu_func_000047F0, "spu_func_000047F0" },
    { 0x000047F8u, spu_func_000047F8, "spu_func_000047F8" },
    { 0x00004968u, spu_func_00004968, "spu_func_00004968" },
    { 0x000049B0u, spu_func_000049B0, "spu_func_000049B0" },
    { 0x00004BD0u, spu_func_00004BD0, "spu_func_00004BD0" },
    { 0x00004BE0u, spu_func_00004BE0, "spu_func_00004BE0" },
    { 0x00004C64u, spu_func_00004C64, "spu_func_00004C64" },
    { 0x00004C68u, spu_func_00004C68, "spu_func_00004C68" },
    { 0x00004C8Cu, spu_func_00004C8C, "spu_func_00004C8C" },
    { 0x00004CB8u, spu_func_00004CB8, "spu_func_00004CB8" },
    { 0x00004CF4u, spu_func_00004CF4, "spu_func_00004CF4" },
    { 0x00004D08u, spu_func_00004D08, "spu_func_00004D08" },
    { 0x00004D20u, spu_func_00004D20, "spu_func_00004D20" },
    { 0x00004D30u, spu_func_00004D30, "spu_func_00004D30" },
    { 0x00004D40u, spu_func_00004D40, "spu_func_00004D40" },
    { 0x00004D70u, spu_func_00004D70, "spu_func_00004D70" },
    { 0x00004D80u, spu_func_00004D80, "spu_func_00004D80" },
    { 0x00004DE0u, spu_func_00004DE0, "spu_func_00004DE0" },
    { 0x00004DECu, spu_func_00004DEC, "spu_func_00004DEC" },
    { 0x00004E64u, spu_func_00004E64, "spu_func_00004E64" },
    { 0x00004EA8u, spu_func_00004EA8, "spu_func_00004EA8" },
    { 0x00004EBCu, spu_func_00004EBC, "spu_func_00004EBC" },
    { 0x00004ED4u, spu_func_00004ED4, "spu_func_00004ED4" },
    { 0x00004F34u, spu_func_00004F34, "spu_func_00004F34" },
    { 0x00004F4Cu, spu_func_00004F4C, "spu_func_00004F4C" },
    { 0x00004F5Cu, spu_func_00004F5C, "spu_func_00004F5C" },
    { 0x00004F64u, spu_func_00004F64, "spu_func_00004F64" },
    { 0x00004F78u, spu_func_00004F78, "spu_func_00004F78" },
    { 0x00004F84u, spu_func_00004F84, "spu_func_00004F84" },
    { 0x00004F98u, spu_func_00004F98, "spu_func_00004F98" },
    { 0x00004FA0u, spu_func_00004FA0, "spu_func_00004FA0" },
    { 0x00004FF0u, spu_func_00004FF0, "spu_func_00004FF0" },
    { 0x00005010u, spu_func_00005010, "spu_func_00005010" },
    { 0x00005030u, spu_func_00005030, "spu_func_00005030" },
    { 0x00005060u, spu_func_00005060, "spu_func_00005060" },
    { 0x00005090u, spu_func_00005090, "spu_func_00005090" },
    { 0x00005150u, spu_func_00005150, "spu_func_00005150" },
    { 0x00005180u, spu_func_00005180, "spu_func_00005180" },
    { 0, NULL, NULL }
};

void spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
