/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void spu_func_00004000(spu_context* ctx);
void spu_func_00004040(spu_context* ctx);
void spu_func_00004058(spu_context* ctx);
void spu_func_00004078(spu_context* ctx);
void spu_func_00004080(spu_context* ctx);
void spu_func_000040B0(spu_context* ctx);
void spu_func_000040C0(spu_context* ctx);
void spu_func_000040C8(spu_context* ctx);
void spu_func_000040F0(spu_context* ctx);
void spu_func_000040F8(spu_context* ctx);
void spu_func_00004128(spu_context* ctx);
void spu_func_00004200(spu_context* ctx);
void spu_func_000042B0(spu_context* ctx);
void spu_func_00004300(spu_context* ctx);
void spu_func_00004310(spu_context* ctx);
void spu_func_00004358(spu_context* ctx);
void spu_func_00004360(spu_context* ctx);
void spu_func_000043D4(spu_context* ctx);
void spu_func_00004408(spu_context* ctx);
void spu_func_00004438(spu_context* ctx);
void spu_func_00004448(spu_context* ctx);
void spu_func_00004484(spu_context* ctx);
void spu_func_00004490(spu_context* ctx);
void spu_func_000044C8(spu_context* ctx);
void spu_func_000044E0(spu_context* ctx);
void spu_func_000044F0(spu_context* ctx);
void spu_func_000044F8(spu_context* ctx);
void spu_func_00004518(spu_context* ctx);
void spu_func_00004528(spu_context* ctx);
void spu_func_00004538(spu_context* ctx);
void spu_func_00004540(spu_context* ctx);
void spu_func_00004550(spu_context* ctx);
void spu_func_00004554(spu_context* ctx);
void spu_func_0000455C(spu_context* ctx);
void spu_func_00004564(spu_context* ctx);
void spu_func_0000456C(spu_context* ctx);
void spu_func_00004570(spu_context* ctx);
void spu_func_00004588(spu_context* ctx);
void spu_func_000045B8(spu_context* ctx);
void spu_func_000045C0(spu_context* ctx);
void spu_func_000045D8(spu_context* ctx);
void spu_func_00004658(spu_context* ctx);
void spu_func_00004690(spu_context* ctx);
void spu_func_000046C4(spu_context* ctx);
void spu_func_000046D0(spu_context* ctx);
void spu_func_000046E8(spu_context* ctx);
void spu_func_00004750(spu_context* ctx);
void spu_func_00004788(spu_context* ctx);
void spu_func_000047E0(spu_context* ctx);
void spu_func_000047F0(spu_context* ctx);
void spu_func_000047F8(spu_context* ctx);
void spu_func_00004968(spu_context* ctx);
void spu_func_000049B0(spu_context* ctx);
void spu_func_00004BD0(spu_context* ctx);
void spu_func_00004BE0(spu_context* ctx);
void spu_func_00004C64(spu_context* ctx);
void spu_func_00004C68(spu_context* ctx);
void spu_func_00004C8C(spu_context* ctx);
void spu_func_00004CB8(spu_context* ctx);
void spu_func_00004CF4(spu_context* ctx);
void spu_func_00004D08(spu_context* ctx);
void spu_func_00004D20(spu_context* ctx);
void spu_func_00004D30(spu_context* ctx);
void spu_func_00004D40(spu_context* ctx);
void spu_func_00004D70(spu_context* ctx);
void spu_func_00004D80(spu_context* ctx);
void spu_func_00004DE0(spu_context* ctx);
void spu_func_00004DEC(spu_context* ctx);
void spu_func_00004E64(spu_context* ctx);
void spu_func_00004EA8(spu_context* ctx);
void spu_func_00004EBC(spu_context* ctx);
void spu_func_00004ED4(spu_context* ctx);
void spu_func_00004F34(spu_context* ctx);
void spu_func_00004F4C(spu_context* ctx);
void spu_func_00004F5C(spu_context* ctx);
void spu_func_00004F64(spu_context* ctx);
void spu_func_00004F78(spu_context* ctx);
void spu_func_00004F84(spu_context* ctx);
void spu_func_00004F98(spu_context* ctx);
void spu_func_00004FA0(spu_context* ctx);
void spu_func_00004FF0(spu_context* ctx);
void spu_func_00005010(spu_context* ctx);
void spu_func_00005030(spu_context* ctx);
void spu_func_00005060(spu_context* ctx);
void spu_func_00005090(spu_context* ctx);
void spu_func_00005150(spu_context* ctx);
void spu_func_00005180(spu_context* ctx);
void spu_func_00003FE0(spu_context* ctx); /* external */
void spu_func_000041E0(spu_context* ctx); /* external */
void spu_func_00004290(spu_context* ctx); /* external */
void spu_func_000042E0(spu_context* ctx); /* external */
void spu_func_000042F0(spu_context* ctx); /* external */
void spu_func_00004338(spu_context* ctx); /* external */
void spu_func_000043B4(spu_context* ctx); /* external */
void spu_func_000043E8(spu_context* ctx); /* external */
void spu_func_00004418(spu_context* ctx); /* external */
void spu_func_00004464(spu_context* ctx); /* external */
void spu_func_00004470(spu_context* ctx); /* external */
void spu_func_000044C0(spu_context* ctx); /* external */
void spu_func_000044D0(spu_context* ctx); /* external */
void spu_func_00004534(spu_context* ctx); /* external */
void spu_func_0000453C(spu_context* ctx); /* external */
void spu_func_00004544(spu_context* ctx); /* external */
void spu_func_0000454C(spu_context* ctx); /* external */
void spu_func_00004568(spu_context* ctx); /* external */
void spu_func_00004598(spu_context* ctx); /* external */
void spu_func_00004638(spu_context* ctx); /* external */
void spu_func_00004670(spu_context* ctx); /* external */
void spu_func_000046B0(spu_context* ctx); /* external */
void spu_func_000046C8(spu_context* ctx); /* external */
void spu_func_00004730(spu_context* ctx); /* external */
void spu_func_00004768(spu_context* ctx); /* external */
void spu_func_000047C0(spu_context* ctx); /* external */
void spu_func_000047D8(spu_context* ctx); /* external */
void spu_func_00004948(spu_context* ctx); /* external */
void spu_func_00004990(spu_context* ctx); /* external */
void spu_func_00004BB0(spu_context* ctx); /* external */
void spu_func_00004BC0(spu_context* ctx); /* external */
void spu_func_00004C44(spu_context* ctx); /* external */
void spu_func_00004C6C(spu_context* ctx); /* external */
void spu_func_00004C98(spu_context* ctx); /* external */
void spu_func_00004CD4(spu_context* ctx); /* external */
void spu_func_00004CE8(spu_context* ctx); /* external */
void spu_func_00004D10(spu_context* ctx); /* external */
void spu_func_00004DC0(spu_context* ctx); /* external */
void spu_func_00004DCC(spu_context* ctx); /* external */
void spu_func_00004E44(spu_context* ctx); /* external */
void spu_func_00004E9C(spu_context* ctx); /* external */
void spu_func_00004EB4(spu_context* ctx); /* external */
void spu_func_00004F14(spu_context* ctx); /* external */
void spu_func_00004F58(spu_context* ctx); /* external */

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void spu_recomp_register(void);
